import type {
  Family, FamilyMember, CareProvider, CareRequest, Appointment,
  TimelineEntry, Notification, User, Employee, Booking, Emergency, MedicalRecord, CareCategory,
  ProviderServiceItem, AvailabilityConfig, OrganizationProfile, ProviderDocument, ServiceNote,
} from '@/types';

const now = () => new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3600000).toISOString();
const daysFromNow = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

export const mockUsers: User[] = [
  { id: 'user_family_1', name: 'Rajesh Sharma', email: 'rajesh.family@example.com', phone: '+91 98200 12345', role: 'family', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_provider_1', name: 'Dr. Vikram Malhotra (Aastha Care)', email: 'vikram.provider@example.com', phone: '+91 98100 98765', role: 'care-provider', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_employee_1', name: 'Anjali Sharma (Nurse)', email: 'anjali.employee@example.com', phone: '+91 98330 55512', role: 'employee', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_admin_1', name: 'Ananya Verma (Admin)', email: 'admin@lomaa.com', phone: '+91 98000 00000', role: 'admin', isActive: true, createdAt: now(), updatedAt: now() },
];

export const mockCareCategories: CareCategory[] = [
  { id: 'doctor', label: 'Doctor Visit', icon: 'Stethoscope', description: 'Home consultation by qualified physician', color: 'primary', estimatedResponseTime: '15-30 mins' },
  { id: 'hospital', label: 'Hospital Care', icon: 'Building2', description: 'Hospital admission & emergency coordination', color: 'secondary', estimatedResponseTime: 'Immediate' },
  { id: 'caregiver', label: 'Elderly Caregiver', icon: 'Users', description: 'Daily living assistance & companionship', color: 'primary', estimatedResponseTime: '30-45 mins' },
  { id: 'home-nurse', label: 'Home Nursing', icon: 'HeartPulse', description: 'Registered nurse visits for IV & wound care', color: 'secondary', estimatedResponseTime: '20-40 mins' },
  { id: 'medicine', label: 'Medicine Delivery', icon: 'Pill', description: 'Doorstep prescription & OTC delivery', color: 'primary', estimatedResponseTime: '30-60 mins' },
  { id: 'laboratory', label: 'Diagnostic Lab', icon: 'FlaskConical', description: 'At-home blood sample collection', color: 'secondary', estimatedResponseTime: '1-2 hours' },
  { id: 'ambulance', label: 'Ambulance', icon: 'Ambulance', description: 'Emergency medical transport with oxygen', color: 'primary', estimatedResponseTime: '5-10 mins' },
  { id: 'transport', label: 'Senior Transport', icon: 'Car', description: 'Safe vehicle transport for appointments', color: 'secondary', estimatedResponseTime: '15-20 mins' },
  { id: 'electrician', label: 'Home Repairs', icon: 'Zap', description: 'Electrical safety check & grab bars', color: 'primary', estimatedResponseTime: '30-45 mins' },
  { id: 'plumber', label: 'Plumbing Service', icon: 'Wrench', description: 'Sanitary repairs & bathroom safety', color: 'secondary', estimatedResponseTime: '30-45 mins' },
  { id: 'housekeeping', label: 'Housekeeping', icon: 'Home', description: 'Senior room sanitization & cleaning', color: 'primary', estimatedResponseTime: '1-2 hours' },
  { id: 'physiotherapy', label: 'Physiotherapy', icon: 'Activity', description: 'Joint mobility & stroke rehabilitation', color: 'secondary', estimatedResponseTime: '45-60 mins' },
  { id: 'other', label: 'Custom Assistance', icon: 'HandHeart', description: 'Specialized senior care assistance', color: 'primary', estimatedResponseTime: '20-30 mins' },
];

export const mockFamilyMembers: FamilyMember[] = [
  {
    id: 'mem_1', familyId: 'fam_1', name: 'Ramachandra Sharma', relationship: 'Father',
    gender: 'male', dateOfBirth: '1948-05-14', bloodGroup: 'B+',
    medicalConditions: ['Hypertension', 'Type 2 Diabetes'], allergies: ['Penicillin'],
    insurance: { provider: 'Star Health Insurance', policyNumber: 'SH-8891234' },
    emergencyContacts: [{ name: 'Rajesh Sharma', relationship: 'Son', phone: '+91 98200 12345', isPrimary: true }],
    status: 'active', medicalNotes: 'Takes daily insulin & blood pressure medication. Fasting sugar checked every morning.',
    governmentIdType: 'aadhaar', governmentIdNumber: '9988-7766-5544',
    createdAt: daysAgo(90), updatedAt: daysAgo(2),
  },
  {
    id: 'mem_2', familyId: 'fam_1', name: 'Savitri Sharma', relationship: 'Mother',
    gender: 'female', dateOfBirth: '1952-11-03', bloodGroup: 'A+',
    medicalConditions: ['Arthritis', 'Osteoporosis'], allergies: ['Aspirin', 'Latex'],
    insurance: { provider: 'Star Health Insurance', policyNumber: 'SH-8891235' },
    emergencyContacts: [{ name: 'Rajesh Sharma', relationship: 'Son', phone: '+91 98200 12345', isPrimary: true }],
    status: 'active', medicalNotes: 'Physiotherapy required twice a week for knee joints.',
    governmentIdType: 'aadhaar', governmentIdNumber: '8877-6655-4433',
    createdAt: daysAgo(88), updatedAt: daysAgo(5),
  },
  {
    id: 'mem_3', familyId: 'fam_1', name: 'Amit Sharma', relationship: 'Brother',
    gender: 'male', dateOfBirth: '1985-08-22', bloodGroup: 'O+',
    medicalConditions: [], allergies: [],
    insurance: { provider: 'HDFC ERGO Health' },
    emergencyContacts: [],
    status: 'active',
    governmentIdType: 'aadhaar', governmentIdNumber: '7766-5544-3322',
    createdAt: daysAgo(60), updatedAt: daysAgo(10),
  },
];

export const mockFamilies: Family[] = [
  {
    id: 'fam_1', userId: 'user_family_1', name: 'Sharma Family',
    primaryContactName: 'Rajesh Sharma',
    contact: { phone: '+91 98200 12345', email: 'rajesh.family@example.com' },
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    members: mockFamilyMembers,
    emergencyContacts: [{ name: 'Dr. V. K. Joshi (Family Doctor)', relationship: 'Doctor', phone: '+91 22 2840 9999' }],
    createdAt: daysAgo(90), updatedAt: daysAgo(1),
  },
];

export const mockCareProviders: CareProvider[] = [
  {
    id: 'prov_1', name: 'Aastha Senior Home Care & Rehab', type: 'home-care',
    description: 'Premier home healthcare & geriatric support. Experienced registered nurses, certified caregivers, and physiotherapists.',
    contact: { phone: '+91 22 4000 1111', email: 'care@aasthacare.in' },
    address: { line1: 'Linking Road, Bandra West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
    rating: 4.9, reviewCount: 184, isVerified: true,
    services: ['In-Home Nursing', 'Elderly Caregiver', 'Home Doctor Visit', 'Physiotherapy & Rehab', 'Sample Pickup'],
    experienceYears: 14, startingPrice: 1200, currency: '₹', distanceKm: 2.4, estimatedArrivalMinutes: 25, availability: 'available',
    employees: [
      { id: 'emp_prov_1', name: 'Anjali Sharma', role: 'Senior Registered Nurse', experience: '8 years', rating: 4.9, availability: 'Available today' },
      { id: 'emp_prov_2', name: 'Ritu Verma', role: 'Elderly Caregiver', experience: '5 years', rating: 4.7, availability: 'Available tomorrow' },
      { id: 'emp_prov_3', name: 'Rajesh Kumar', role: 'Senior Physiotherapist', experience: '6 years', rating: 4.8, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_1', reviewerName: 'Vikramaditya S.', rating: 5, comment: 'Outstanding home nursing for my father. Anjali was extremely attentive and caring.', createdAt: daysAgo(10) },
      { id: 'rev_2', reviewerName: 'Radhika M.', rating: 5, comment: 'Aastha Care has been supporting our family for 3 years. Most trustworthy service in Mumbai.', createdAt: daysAgo(20) },
      { id: 'rev_3', reviewerName: 'Suresh K.', rating: 4, comment: 'Prompt response and trained staff. My mother is very satisfied.', createdAt: daysAgo(35) },
    ],
    createdAt: daysAgo(200), updatedAt: daysAgo(1),
  },
  {
    id: 'prov_2', name: 'Jan Aushadhi Home Pharmacy', type: 'pharmacy',
    description: 'Fast home delivery of prescription medicines, chronic illness supplies, and OTC healthcare products.',
    contact: { phone: '+91 22 4000 2222', email: 'orders@janaushadhi.in' },
    address: { line1: 'Andheri East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400069', country: 'India' },
    rating: 4.7, reviewCount: 412, isVerified: true,
    services: ['Prescription Delivery', 'Chronic Medicine Refills', 'Medical Supplies', 'Refill Alerts'],
    experienceYears: 8, startingPrice: 200, currency: '₹', distanceKm: 3.8, estimatedArrivalMinutes: 45, availability: 'available',
    reviews: [
      { id: 'rev_4', reviewerName: 'Sneha P.', rating: 5, comment: 'Delivered within 40 minutes. Original medicines with proper invoice.', createdAt: daysAgo(5) },
    ],
    createdAt: daysAgo(150), updatedAt: daysAgo(3),
  },
  {
    id: 'prov_3', name: 'Sanjivani Diagnostic Labs', type: 'laboratory',
    description: 'NABL-accredited diagnostic laboratory with morning home sample collection and online reports within 12 hours.',
    contact: { phone: '+91 22 4000 3333', email: 'reports@sanjivanilab.in' },
    address: { line1: 'Powai Central', city: 'Mumbai', state: 'Maharashtra', postalCode: '400076', country: 'India' },
    rating: 4.85, reviewCount: 290, isVerified: true,
    services: ['Blood Test Collection', 'HbA1c & Lipid Panel', 'ECG at Home', 'Radiology Pickup'],
    experienceYears: 10, startingPrice: 600, currency: '₹', distanceKm: 4.5, estimatedArrivalMinutes: 60, availability: 'available',
    reviews: [
      { id: 'rev_5', reviewerName: 'Dr. Meenakshi S.', rating: 5, comment: 'Punctual phlebotomist and very accurate reports.', createdAt: daysAgo(8) },
    ],
    createdAt: daysAgo(180), updatedAt: daysAgo(2),
  },
  {
    id: 'prov_4', name: 'Chaitanya Rehab & Physio Center', type: 'physiotherapy',
    description: 'Specialized geriatric physiotherapy, knee/hip replacement rehab, stroke recovery, and posture correction.',
    contact: { phone: '+91 22 4000 4444', email: 'physio@chaitanya.in' },
    address: { line1: 'Juhu Tara Road', city: 'Mumbai', state: 'Maharashtra', postalCode: '400049', country: 'India' },
    rating: 4.8, reviewCount: 115, isVerified: true,
    services: ['Physiotherapy', 'Stroke Rehabilitation', 'Post-Surgery Rehab', 'Pain Relief Therapy'],
    experienceYears: 9, startingPrice: 1500, currency: '₹', distanceKm: 3.2, estimatedArrivalMinutes: 40, availability: 'busy',
    reviews: [],
    createdAt: daysAgo(120), updatedAt: daysAgo(4),
  },
  {
    id: 'prov_5', name: 'Dr. Malhotra House Call Physicians', type: 'doctor',
    description: 'Senior general physicians and geriatric specialists providing comprehensive medical consultations at home 24/7.',
    contact: { phone: '+91 22 4000 5555', email: 'doc@malhotracare.in' },
    address: { line1: 'Lower Parel', city: 'Mumbai', state: 'Maharashtra', postalCode: '400013', country: 'India' },
    rating: 4.95, reviewCount: 560, isVerified: true,
    services: ['Home Doctor Visit', 'Geriatric Health Review', 'Prescription Renewal', 'Emergency Doctor Response'],
    experienceYears: 18, startingPrice: 2500, currency: '₹', distanceKm: 1.9, estimatedArrivalMinutes: 20, availability: 'available',
    employees: [
      { id: 'emp_prov_4', name: 'Dr. Alok Gupta', role: 'Senior General Physician', experience: '15 years', rating: 4.95, availability: 'Available now' },
      { id: 'emp_prov_5', name: 'Dr. Sunita Rao', role: 'Geriatric Specialist', experience: '20 years', rating: 4.9, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_6', reviewerName: 'Ramesh R.', rating: 5, comment: 'Dr. Alok examined my elderly father thoroughly. Very compassionate and empathetic.', createdAt: daysAgo(3) },
    ],
    createdAt: daysAgo(365), updatedAt: now(),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt_1', familyId: 'fam_1', memberId: 'mem_1', providerId: 'prov_5',
    providerName: 'Dr. Malhotra House Call Physicians — Dr. Alok Gupta', serviceType: 'Doctor Consultation',
    scheduledAt: daysFromNow(1), durationMinutes: 45, status: 'upcoming',
    notes: 'Monthly diabetes and vital checkup', location: 'Gokuldham Heights Flat 402',
    createdAt: hoursAgo(5), updatedAt: hoursAgo(4),
  },
  {
    id: 'apt_2', familyId: 'fam_1', memberId: 'mem_2', providerId: 'prov_4',
    providerName: 'Chaitanya Rehab — Rajesh Kumar', serviceType: 'Physiotherapy Session',
    scheduledAt: daysFromNow(3), durationMinutes: 60, status: 'upcoming',
    notes: 'Knee joint mobility session', location: 'Gokuldham Heights Flat 402',
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    id: 'apt_3', familyId: 'fam_1', memberId: 'mem_1', providerId: 'prov_3',
    providerName: 'Sanjivani Diagnostic Labs', serviceType: 'Blood Test Collection',
    scheduledAt: daysAgo(7), durationMinutes: 20, status: 'completed',
    notes: 'Fasting Glucose & HbA1c Panel', location: 'Home Collection',
    createdAt: daysAgo(10), updatedAt: daysAgo(7),
  },
];

export const mockTimeline: TimelineEntry[] = [
  { id: 'tl_1', familyId: 'fam_1', memberId: 'mem_1', eventType: 'care-request-submitted', title: 'Care Request Submitted', description: 'Home doctor consultation for Ramachandra Sharma requested.', createdAt: hoursAgo(5), updatedAt: hoursAgo(5) },
  { id: 'tl_2', familyId: 'fam_1', memberId: 'mem_1', eventType: 'care-request-accepted', title: 'Request Confirmed', description: 'Aastha Senior Care accepted the doctor visit request.', createdAt: hoursAgo(4), updatedAt: hoursAgo(4) },
  { id: 'tl_3', familyId: 'fam_1', memberId: 'mem_2', eventType: 'care-request-completed', title: 'Physiotherapy Completed', description: 'Physiotherapy session for Savitri Sharma completed.', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'tl_4', familyId: 'fam_1', memberId: 'mem_1', eventType: 'lab-test', title: 'Diagnostic Report Ready', description: 'HbA1c report available for Ramachandra Sharma.', createdAt: daysAgo(7), updatedAt: daysAgo(7) },
  { id: 'tl_5', familyId: 'fam_1', memberId: 'mem_1', eventType: 'medicine-delivered', title: 'Medicines Delivered', description: 'Monthly diabetes refill delivered by Jan Aushadhi.', createdAt: daysAgo(10), updatedAt: daysAgo(10) },
];

export const mockNotifications: Notification[] = [
  { id: 'notif_1', userId: 'user_family_1', title: 'Care Request Accepted', message: 'Aastha Senior Care has confirmed your request. Nurse Anjali will arrive tomorrow at 10:00 AM.', read: false, type: 'success', createdAt: hoursAgo(4), updatedAt: hoursAgo(4) },
  { id: 'notif_2', userId: 'user_family_1', title: 'Doctor Visit Tomorrow', message: 'Reminder: Dr. Alok Gupta visit for Ramachandra Sharma is scheduled for tomorrow at 10:00 AM.', read: false, type: 'info', createdAt: hoursAgo(2), updatedAt: hoursAgo(2) },
  { id: 'notif_3', userId: 'user_family_1', title: 'Physiotherapy Session In Progress', message: 'Rajesh Kumar has started the knee therapy session for Savitri Sharma.', read: true, type: 'info', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'notif_4', userId: 'user_family_1', title: 'Lab Results Uploaded', message: 'Fasting glucose results for Ramachandra Sharma are ready for viewing.', read: true, type: 'warning', createdAt: daysAgo(7), updatedAt: daysAgo(7) },
  { id: 'notif_5', userId: 'user_family_1', title: 'Medicine Delivery Complete', message: 'Insulin and hypertension kit delivered by Jan Aushadhi Pharmacy.', read: true, type: 'success', createdAt: daysAgo(10), updatedAt: daysAgo(10) },
  { id: 'notif_6', userId: 'user_family_1', title: 'Service Visit Completed', message: 'Home nursing visit by Nurse Anjali Sharma completed successfully.', read: true, type: 'success', createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: 'notif_7', userId: 'user_provider_1', title: 'New Care Request', message: 'Urgent caregiver request received for Devendra Patel.', read: false, type: 'warning', createdAt: hoursAgo(0.2), updatedAt: hoursAgo(0.2) },
  { id: 'notif_8', userId: 'user_provider_1', title: 'Staff On The Way', message: 'Nurse Anjali Sharma marked status as On The Way to Ramachandra Sharma residence.', read: false, type: 'info', createdAt: hoursAgo(0.3), updatedAt: hoursAgo(0.3) },
  { id: 'notif_9', userId: 'user_employee_1', title: 'New Field Assignment', message: 'You have been assigned to visit Ramachandra Sharma for Home Nursing Care.', read: false, type: 'success', createdAt: hoursAgo(1), updatedAt: hoursAgo(1) },
  { id: 'notif_10', userId: 'user_provider_1', title: '5-Star Review Received', message: 'Vikramaditya S. left a 5-star review for Anjali Sharma.', read: true, type: 'success', createdAt: daysAgo(5), updatedAt: daysAgo(5) },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp_1',
    name: 'Anjali Sharma',
    role: 'Senior Registered Nurse',
    department: 'Home Nursing Care',
    experience: '8 years',
    licenseNumber: 'INC-RN-88219-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98330 55512', email: 'anjali.s@aasthacare.in' },
    address: { line1: 'Dadar West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400028', country: 'India' },
    languages: ['Hindi', 'English', 'Marathi'],
    availability: 'available',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
    workingHours: '08:00 AM - 05:00 PM',
    governmentIdType: 'national-id',
    governmentIdNumber: '7841-1988-1234-1590',
    certificates: ['B.Sc Nursing', 'Basic Life Support (BLS)', 'Geriatric Care Specialist'],
    emergencyContact: { name: 'Suresh Sharma', relationship: 'Brother', phone: '+91 98220 99887' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-7885a3964478?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    reviewCount: 42,
    assignedRequestsCount: 3,
    completedRequestsCount: 156,
    specialization: ['Geriatric Nursing', 'Wound Dressing', 'Diabetes Care'],
    createdAt: daysAgo(365),
    updatedAt: now(),
  },
  {
    id: 'emp_2',
    name: 'Ritu Verma',
    role: 'Elderly Caregiver',
    department: 'Home Care Services',
    experience: '5 years',
    licenseNumber: 'CG-45210-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98211 44322', email: 'ritu.v@aasthacare.in' },
    address: { line1: 'Goregaon East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    languages: ['Hindi', 'English'],
    availability: 'busy',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '09:00 AM - 06:00 PM',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '9988-1122-3344',
    certificates: ['Senior Companionship Certified', 'First Aid & CPR'],
    emergencyContact: { name: 'Kavita Verma', relationship: 'Sister', phone: '+91 98211 22110' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    rating: 4.7,
    reviewCount: 31,
    assignedRequestsCount: 2,
    completedRequestsCount: 104,
    specialization: ['Daily Living Support', 'Mobility Assistance', 'Dementia Support'],
    createdAt: daysAgo(300),
    updatedAt: now(),
  },
  {
    id: 'emp_3',
    name: 'Rajesh Kumar',
    role: 'Senior Physiotherapist',
    department: 'Rehabilitation',
    experience: '6 years',
    licenseNumber: 'BPT-99312-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98335 88766', email: 'rajesh.k@aasthacare.in' },
    address: { line1: 'Mulund West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400080', country: 'India' },
    languages: ['Hindi', 'English', 'Marathi', 'Gujarati'],
    availability: 'available',
    workingDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    workingHours: '08:00 AM - 04:00 PM',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '5544-3322-1100',
    certificates: ['Master of Physiotherapy (MPT)', 'Stroke Rehabilitation Specialist'],
    emergencyContact: { name: 'Pooja Kumar', relationship: 'Wife', phone: '+91 98335 33445' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    rating: 4.85,
    reviewCount: 50,
    assignedRequestsCount: 1,
    completedRequestsCount: 128,
    specialization: ['Stroke Recovery', 'Knee/Joint Rehab', 'Posture Correction'],
    createdAt: daysAgo(250),
    updatedAt: now(),
  },
  {
    id: 'emp_4',
    name: 'Dr. Alok Gupta',
    role: 'General Physician',
    department: 'Medical Consultations',
    experience: '15 years',
    licenseNumber: 'MCI-MD-44812',
    providerId: 'prov_1',
    contact: { phone: '+91 98110 99900', email: 'alok.g@aasthacare.in' },
    address: { line1: 'Bandra Reclamation', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
    languages: ['Hindi', 'English'],
    availability: 'emergency_duty',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    workingHours: '24/7 On-Call Doctor',
    governmentIdType: 'national-id',
    governmentIdNumber: '7841-1982-9988-7766',
    certificates: ['MD Internal Medicine', 'Geriatric Health Specialist'],
    emergencyContact: { name: 'Dr. Meera Gupta', relationship: 'Wife', phone: '+91 98110 22110' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    rating: 4.95,
    reviewCount: 88,
    assignedRequestsCount: 4,
    completedRequestsCount: 260,
    specialization: ['Geriatric Care', 'Chronic Disease Management', 'Emergency Medicine'],
    createdAt: daysAgo(400),
    updatedAt: now(),
  },
  {
    id: 'emp_5',
    name: 'Suresh Patel',
    role: 'Emergency Medical Technician',
    department: 'Ambulance & Transport',
    experience: '7 years',
    licenseNumber: 'EMT-66120-MUM',
    providerId: 'prov_1',
    contact: { phone: '+971 98663 39988', email: 'suresh.p@aasthacare.in' },
    address: { line1: 'Thane West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400601', country: 'India' },
    languages: ['Hindi', 'English', 'Gujarati'],
    availability: 'available',
    workingDays: ['Everyday'],
    workingHours: 'Rotational Shift',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '1122-3344-5566',
    certificates: ['Advanced Cardiac Life Support (ACLS)', 'Emergency Paramedic Level II'],
    emergencyContact: { name: 'Dinesh Patel', relationship: 'Father', phone: '+91 98663 44322' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
    rating: 4.85,
    reviewCount: 35,
    assignedRequestsCount: 0,
    completedRequestsCount: 95,
    specialization: ['Oxygen Administration', 'Trauma Response', 'Emergency Patient Transfer'],
    createdAt: daysAgo(180),
    updatedAt: now(),
  },
];

export const mockCareRequests: CareRequest[] = [
  {
    id: 'req_101',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_1',
    patientName: 'Ramachandra Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_1',
    employeeName: 'Anjali Sharma',
    employeeRole: 'Senior Registered Nurse',
    employeePhone: '+91 98330 55512',
    category: 'home-nurse',
    categoryLabel: 'Home Nurse Care',
    priority: 'urgent',
    status: 'on_the_way',
    scheduledAt: now(),
    notes: 'Urgent wound dressing & blood pressure vital check.',
    medicalNotes: 'Hypertension & Type 2 Diabetes. Patient takes morning insulin. Sensitive skin near knee area.',
    internalNotes: ['Family requested female nurse.', 'Assigned Anjali Sharma at 09:15 AM.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 1500,
    currency: '₹',
    estimatedArrivalMinutes: 12,
    estimatedDuration: '45 mins',
    timeline: [
      { status: 'pending', title: 'Request Submitted', description: 'Family requested urgent home nursing visit.', timestamp: hoursAgo(2) },
      { status: 'accepted', title: 'Request Accepted', description: 'Aastha Senior Care accepted the request.', timestamp: hoursAgo(1.5) },
      { status: 'employee_assigned', title: 'Nurse Assigned', description: 'Nurse Anjali Sharma assigned to visit.', timestamp: hoursAgo(1) },
      { status: 'on_the_way', title: 'Nurse On The Way', description: 'Anjali is en route with medical kit.', timestamp: hoursAgo(0.3) },
    ],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(0.3),
  },
  {
    id: 'req_102',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_2',
    patientName: 'Savitri Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_3',
    employeeName: 'Rajesh Kumar',
    employeeRole: 'Senior Physiotherapist',
    employeePhone: '+91 98335 88766',
    category: 'physiotherapy',
    categoryLabel: 'Physiotherapy Session',
    priority: 'standard',
    status: 'in_progress',
    scheduledAt: hoursAgo(1),
    notes: 'Bi-weekly knee arthritis mobility session.',
    medicalNotes: 'Severe joint stiffness in right knee. Avoid heavy weight bearing exercises.',
    internalNotes: ['Patient responded very well to warm up routine last session.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 1800,
    currency: '₹',
    estimatedArrivalMinutes: 0,
    estimatedDuration: '60 mins',
    timeline: [
      { status: 'pending', title: 'Booking Confirmed', description: 'Scheduled physiotherapy booked.', timestamp: daysAgo(1) },
      { status: 'accepted', title: 'Accepted', description: 'Provider confirmed slot.', timestamp: daysAgo(1) },
      { status: 'employee_assigned', title: 'Physiotherapist Assigned', description: 'Rajesh Kumar assigned.', timestamp: hoursAgo(3) },
      { status: 'arrived', title: 'Arrived at Location', description: 'Rajesh reached patient home.', timestamp: hoursAgo(1) },
      { status: 'in_progress', title: 'Session Started', description: 'Therapy exercises currently underway.', timestamp: hoursAgo(0.8) },
    ],
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(0.8),
  },
  {
    id: 'req_103',
    familyId: 'fam_1',
    familyName: 'Patel Family',
    memberId: 'mem_4',
    patientName: 'Devendra Patel',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    category: 'caregiver',
    categoryLabel: 'Caregiver Companionship',
    priority: 'emergency',
    status: 'pending',
    scheduledAt: daysFromNow(0.2),
    notes: 'Emergency caregiver needed due to family out of station.',
    medicalNotes: 'Dementia stage 1. Requires constant supervision & medication reminders.',
    internalNotes: [],
    address: { line1: 'Vasant Vihar Society 14', city: 'Mumbai', state: 'Maharashtra', postalCode: '400053', country: 'India' },
    estimatedCost: 1200,
    currency: '₹',
    estimatedArrivalMinutes: 20,
    estimatedDuration: '4 hours',
    timeline: [
      { status: 'pending', title: 'Emergency Request Submitted', description: 'Waiting for provider acceptance.', timestamp: hoursAgo(0.2) },
    ],
    createdAt: hoursAgo(0.2),
    updatedAt: hoursAgo(0.2),
  },
  {
    id: 'req_104',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_1',
    patientName: 'Ramachandra Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_4',
    employeeName: 'Dr. Alok Gupta',
    employeeRole: 'General Physician',
    employeePhone: '+91 98110 99900',
    category: 'doctor',
    categoryLabel: 'Doctor Consultation',
    priority: 'scheduled',
    status: 'accepted',
    scheduledAt: daysFromNow(1),
    notes: 'Monthly diabetes and blood pressure evaluation.',
    medicalNotes: 'Diabetic history. Brings logbook of daily fasting glucose readings.',
    internalNotes: ['Dr. Alok confirmed schedule for tomorrow 10:00 AM.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 2500,
    currency: '₹',
    estimatedArrivalMinutes: 30,
    estimatedDuration: '45 mins',
    timeline: [
      { status: 'pending', title: 'Request Submitted', description: 'Doctor visit requested for tomorrow.', timestamp: hoursAgo(5) },
      { status: 'accepted', title: 'Request Accepted', description: 'Dr. Alok Gupta assigned & confirmed slot.', timestamp: hoursAgo(4) },
    ],
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'req_105',
    familyId: 'fam_1',
    familyName: 'Joshi Family',
    memberId: 'mem_5',
    patientName: 'Sunita Joshi',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_1',
    employeeName: 'Anjali Sharma',
    employeeRole: 'Senior Registered Nurse',
    employeePhone: '+91 98330 55512',
    category: 'home-nurse',
    categoryLabel: 'Home Nurse Care',
    priority: 'standard',
    status: 'completed',
    scheduledAt: daysAgo(2),
    notes: 'IV fluid administration & general vital assessment.',
    medicalNotes: 'Mild dehydration. Administered 500ml Normal Saline as per prescription.',
    internalNotes: ['Completed smoothly. Patient felt much better.'],
    address: { line1: 'Shivaji Park, Building 5', city: 'Mumbai', state: 'Maharashtra', postalCode: '400028', country: 'India' },
    estimatedCost: 2000,
    currency: '₹',
    estimatedArrivalMinutes: 0,
    estimatedDuration: '90 mins',
    timeline: [
      { status: 'pending', title: 'Request Created', description: 'Nurse visit requested.', timestamp: daysAgo(3) },
      { status: 'accepted', title: 'Accepted', description: 'Provider confirmed.', timestamp: daysAgo(2.5) },
      { status: 'employee_assigned', title: 'Assigned', description: 'Nurse Anjali assigned.', timestamp: daysAgo(2.2) },
      { status: 'in_progress', title: 'In Progress', description: 'IV drip started.', timestamp: daysAgo(2) },
      { status: 'completed', title: 'Completed', description: 'Drip completed & vital signs stable.', timestamp: daysAgo(2) },
      { status: 'awaiting_review', title: 'Awaiting Review', description: 'Review link sent to family.', timestamp: daysAgo(2) },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
];

export const mockProviderServices: ProviderServiceItem[] = [
  { id: 'srv_1', name: 'In-Home Nursing Care', category: 'Home Nursing', description: 'Certified RN visits for wound care, injections, IV therapy & vital monitoring.', icon: 'HeartPulse', enabled: true, pricing: { amount: 1500, unit: 'per visit', currency: '₹' }, responseTime: '15-30 mins', coverageArea: 'Mumbai Metropolitan & Suburbs' },
  { id: 'srv_2', name: 'Elderly Caregiver Support', category: 'Caregiver', description: 'Compassionate assistance with daily living, hygiene, mobility & companionship.', icon: 'Users', enabled: true, pricing: { amount: 1000, unit: 'per 4 hrs', currency: '₹' }, responseTime: '30-45 mins', coverageArea: 'All Mumbai Zones' },
  { id: 'srv_3', name: 'Home Doctor Consultation', category: 'Doctor', description: 'Board-certified physicians for comprehensive health checkups & prescriptions at home.', icon: 'Stethoscope', enabled: true, pricing: { amount: 2500, unit: 'per visit', currency: '₹' }, responseTime: '20-40 mins', coverageArea: 'Mumbai & Thane' },
  { id: 'srv_4', name: 'Physiotherapy & Rehab', category: 'Physiotherapy', description: 'Customized physical rehabilitation for arthritis, post-stroke & joint mobility.', icon: 'Activity', enabled: true, pricing: { amount: 1800, unit: 'per session', currency: '₹' }, responseTime: '45-60 mins', coverageArea: 'Greater Mumbai' },
  { id: 'srv_5', name: 'Emergency Ambulance Transport', category: 'Ambulance', description: 'Rapid emergency dispatch with ICU-equipped ambulance & paramedic team.', icon: 'Ambulance', enabled: true, pricing: { amount: 3000, unit: 'per callout', currency: '₹' }, responseTime: '5-10 mins', coverageArea: '24/7 Citywide Coverage' },
  { id: 'srv_6', name: 'Diagnostic Lab Sample Pickup', category: 'Diagnostic Lab', description: 'Hygienic blood & sample collection at home with fast online lab results.', icon: 'FlaskConical', enabled: true, pricing: { amount: 600, unit: 'per pickup', currency: '₹' }, responseTime: '60 mins', coverageArea: 'All Districts' },
  { id: 'srv_7', name: 'Prescription Medicine Delivery', category: 'Pharmacy', description: 'Same-day home delivery of prescribed medications and OTC health supplies.', icon: 'Pill', enabled: true, pricing: { amount: 200, unit: 'per delivery', currency: '₹' }, responseTime: '30-60 mins', coverageArea: 'All Pin Codes' },
  { id: 'srv_8', name: 'Senior Wheelchair Transport', category: 'Transportation', description: 'Wheelchair-accessible vehicle transport for hospital visits & appointments.', icon: 'Car', enabled: true, pricing: { amount: 1200, unit: 'per trip', currency: '₹' }, responseTime: '20-30 mins', coverageArea: 'City Limits' },
  { id: 'srv_9', name: 'Senior Home Safety & Maintenance', category: 'Home Maintenance', description: 'Safety inspection, minor repairs, bathroom grab bar installation & light fixes.', icon: 'Wrench', enabled: true, pricing: { amount: 800, unit: 'per visit', currency: '₹' }, responseTime: '45 mins', coverageArea: 'Residential Complexes' },
  { id: 'srv_10', name: 'Senior Housekeeping & Sanitization', category: 'Housekeeping', description: 'Dust-free cleaning, linen changing & allergen sanitization for senior rooms.', icon: 'Home', enabled: false, pricing: { amount: 1000, unit: 'per session', currency: '₹' }, responseTime: '2 hours', coverageArea: 'Selected Pincodes' },
];

export const mockAvailabilityConfig: AvailabilityConfig = {
  businessHours: [
    { day: 'Monday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Tuesday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Wednesday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Thursday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Friday', open: '08:00', close: '18:00', isClosed: false },
    { day: 'Saturday', open: '09:00', close: '18:00', isClosed: false },
    { day: 'Sunday', open: '09:00', close: '16:00', isClosed: false },
  ],
  emergencyAvailable: true,
  holidaySchedule: [
    { date: '2026-08-15', name: 'Independence Day', isClosed: false },
    { date: '2026-10-02', name: 'Gandhi Jayanti', isClosed: true },
    { date: '2026-11-01', name: 'Diwali', isClosed: false },
  ],
  closedDays: ['Public Holidays (Restricted Hours)'],
  coverageRadiusKm: 35,
};

export const mockOrganizationProfile: OrganizationProfile = {
  id: 'prov_1',
  logoUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=200',
  name: 'Aastha Senior Home Care & Medical Services',
  registrationNumber: 'REG-MH-2012-9981',
  gstNumber: '27AAAAA0000A1Z5',
  verificationStatus: 'verified',
  address: { line1: 'Linking Road, Suite 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
  contact: { phone: '+91 22 4000 1111', email: 'care@aasthacare.in', alternativePhone: '+91 98100 98765' },
  website: 'https://aasthacare.in',
  businessHours: '08:00 AM - 08:00 PM (24/7 Emergency Response)',
  serviceCategories: ['Home Nursing', 'Elderly Caregiver', 'Physiotherapy', 'Doctor Visit', 'Emergency Ambulance'],
};

export const mockProviderDocuments: ProviderDocument[] = [
  { id: 'doc_1', title: 'Medical Facility License', type: 'license', fileName: 'Maharashtra_Medical_License_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(120), verificationStatus: 'verified', notes: 'Valid until Dec 2027' },
  { id: 'doc_2', title: 'Commercial Registration Certificate', type: 'registration', fileName: 'Registration_Certificate_Aastha.pdf', fileUrl: '#', uploadedAt: daysAgo(200), verificationStatus: 'verified' },
  { id: 'doc_3', title: 'GST Registration Certificate', type: 'gst', fileName: 'GST_Certificate_27AAAAA.pdf', fileUrl: '#', uploadedAt: daysAgo(200), verificationStatus: 'verified' },
  { id: 'doc_4', title: 'Medical Liability Insurance Policy', type: 'insurance', fileName: 'Medical_Liability_Insurance_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(45), verificationStatus: 'verified', notes: 'Coverage up to ₹50,00,000' },
  { id: 'doc_5', title: 'Staff Nursing License Certifications', type: 'employee', fileName: 'Staff_INC_Certificates_Q1.pdf', fileUrl: '#', uploadedAt: daysAgo(10), verificationStatus: 'verified' },
];

export const mockProviderReviewsExtended = [
  { id: 'rev_1', reviewerName: 'Vikramaditya S.', patientName: 'Ramachandra Sharma', rating: 5, comment: 'Exceptional care for my father. Nurse Anjali was patient, professional and extremely gentle.', createdAt: daysAgo(5), response: { text: 'Thank you Vikramaditya! It is our honor to support your father.', respondedAt: daysAgo(4) } },
  { id: 'rev_2', reviewerName: 'Radhika M.', patientName: 'Savitri Sharma', rating: 5, comment: 'We have used Aastha Care for two years. Best elderly care provider in Mumbai by far.', createdAt: daysAgo(12), response: undefined },
  { id: 'rev_3', reviewerName: 'Suresh K.', patientName: 'Tariq R.', rating: 4, comment: 'Reliable and trustworthy team. Response time for physiotherapy was very prompt.', createdAt: daysAgo(20), response: { text: 'We appreciate your valuable feedback Suresh!', respondedAt: daysAgo(19) } },
  { id: 'rev_4', reviewerName: 'Youssef B.', patientName: 'Amina B.', rating: 5, comment: 'Doctor consultation at home saved us an emergency hospital visit. Truly peace of mind.', createdAt: daysAgo(28), response: undefined },
];

export const mockServiceNotes: ServiceNote[] = [
  {
    id: 'sn_1',
    requestId: 'req_105',
    employeeId: 'emp_1',
    visitNotes: 'Administered IV hydration saline 500ml. Blood pressure 125/82, Heart rate 74 bpm. Temperature 36.8°C.',
    observations: 'Patient was initially fatigued but showed immediate energy recovery post hydration.',
    recommendations: 'Continue daily water intake of at least 2 liters. Recheck blood pressure in 3 days.',
    followUpNeeded: true,
    followUpDetails: 'Schedule follow up blood test if fatigue recurs.',
    attachments: [{ name: 'Vitals_Report_Sunita.pdf', url: '#' }],
    createdAt: daysAgo(2),
  },
];

export const mockBookings: Booking[] = [
  { id: 'book_1', familyId: 'fam_1', providerId: 'prov_1', serviceType: 'home-care', scheduledAt: now(), status: 'completed', employeeId: 'emp_1', createdAt: daysAgo(5), updatedAt: daysAgo(3) },
];

export const mockEmergencies: Emergency[] = [];
export const mockMedicalRecords: any[] = [];
