import type {
  Family, FamilyMember, CareProvider, CareRequest, Appointment,
  TimelineEntry, Notification, User, Employee, Booking, Emergency, MedicalRecord, CareCategory,
  ProviderServiceItem, AvailabilityConfig, OrganizationProfile, ProviderDocument, ServiceNote,
} from '@/types';

const now = () => new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3600000).toISOString();
const daysFromNow = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

export const mockUsers: User[] = [
  { id: 'user_family_1', name: 'Rajesh Sharma', email: 'rajesh.family@example.com', phone: '+91 98200 12345', role: 'family', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_provider_1', name: 'Dr. Vikram Malhotra (Aastha Care)', email: 'vikram.provider@example.com', phone: '+91 98100 98765', role: 'care-provider', avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_employee_1', name: 'Anjali Sharma (Nurse)', email: 'anjali.employee@example.com', phone: '+91 98330 55512', role: 'employee', avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300', isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'user_admin_1', name: 'Ananya Verma (Administrator)', email: 'admin@lomaa.com', phone: '+91 98000 00000', role: 'admin', avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300', isActive: true, createdAt: now(), updatedAt: now() },
];

export const mockCareCategories: CareCategory[] = [
  { id: 'doctor', label: 'Doctor Visit', icon: 'Stethoscope', description: 'Home consultation by qualified physician', color: 'primary', estimatedResponseTime: '15-30 mins' },
  { id: 'hospital', label: 'Hospital Care', icon: 'Building2', description: 'Hospital admission & emergency coordination', color: 'secondary', estimatedResponseTime: 'Immediate' },
  { id: 'caregiver', label: 'Elderly Caregiver', icon: 'Users', description: 'Daily living assistance & companionship', color: 'primary', estimatedResponseTime: '30-45 mins' },
  { id: 'home-nurse', label: 'Home Nursing', icon: 'HeartPulse', description: 'Registered nurse visits for IV & wound care', color: 'secondary', estimatedResponseTime: '20-40 mins' },
  { id: 'medicine', label: 'Medicine Delivery', icon: 'Pill', description: 'Doorstep prescription & OTC delivery', color: 'primary', estimatedResponseTime: '30-60 mins' },
  { id: 'laboratory', label: 'Diagnostic Lab', icon: 'FlaskConical', description: 'At-home blood sample collection', color: 'secondary', estimatedResponseTime: '1-2 hours' },
  { id: 'ambulance', label: 'Ambulance', icon: 'Ambulance', description: 'Emergency medical transport with oxygen', color: 'primary', estimatedResponseTime: '5-10 mins' },
  { id: 'transport', label: 'Senior Transport', icon: 'Car', description: 'Safe vehicle transport for appointments', color: 'secondary', estimatedResponseTime: '15-20 mins' },
  { id: 'electrician', label: 'Home Repairs', icon: 'Zap', description: 'Electrical safety check & grab bars', color: 'primary', estimatedResponseTime: '30-45 mins' },
  { id: 'plumber', label: 'Plumbing Service', icon: 'Wrench', description: 'Sanitary repairs & bathroom safety', color: 'secondary', estimatedResponseTime: '30-45 mins' },
  { id: 'housekeeping', label: 'Housekeeping', icon: 'Home', description: 'Senior room sanitization & cleaning', color: 'primary', estimatedResponseTime: '1-2 hours' },
  { id: 'physiotherapy', label: 'Physiotherapy', icon: 'Activity', description: 'Joint mobility & stroke rehabilitation', color: 'secondary', estimatedResponseTime: '45-60 mins' },
  { id: 'other', label: 'Custom Assistance', icon: 'HandHeart', description: 'Specialized senior care assistance', color: 'primary', estimatedResponseTime: '20-30 mins' },
];

export const mockFamilyMembers: FamilyMember[] = [
  {
    id: 'mem_1', familyId: 'fam_1', name: 'Ramachandra Sharma', relationship: 'Father', avatarUrl: 'https://images.unsplash.com/photo-1584999734482-0361aecad844?auto=format&fit=crop&q=80&w=300',
    gender: 'male', dateOfBirth: '1948-05-14', bloodGroup: 'B+',
    medicalConditions: ['Hypertension', 'Type 2 Diabetes'], allergies: ['Penicillin'],
    insurance: { provider: 'Star Health Insurance', policyNumber: 'SH-8891234' },
    emergencyContacts: [{ name: 'Rajesh Sharma', relationship: 'Son', phone: '+91 98200 12345', isPrimary: true }],
    status: 'active', medicalNotes: 'Takes daily insulin & blood pressure medication. Fasting sugar checked every morning.',
    governmentIdType: 'aadhaar', governmentIdNumber: '9988-7766-5544',
    createdAt: daysAgo(90), updatedAt: daysAgo(2),
  },
  {
    id: 'mem_2', familyId: 'fam_1', name: 'Savitri Sharma', relationship: 'Mother', avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    gender: 'female', dateOfBirth: '1952-11-03', bloodGroup: 'A+',
    medicalConditions: ['Arthritis', 'Osteoporosis'], allergies: ['Aspirin', 'Latex'],
    insurance: { provider: 'Star Health Insurance', policyNumber: 'SH-8891235' },
    emergencyContacts: [{ name: 'Rajesh Sharma', relationship: 'Son', phone: '+91 98200 12345', isPrimary: true }],
    status: 'active', medicalNotes: 'Physiotherapy required twice a week for knee joints.',
    governmentIdType: 'aadhaar', governmentIdNumber: '8877-6655-4433',
    createdAt: daysAgo(88), updatedAt: daysAgo(5),
  },
  {
    id: 'mem_3', familyId: 'fam_1', name: 'Amit Sharma', relationship: 'Brother', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    gender: 'male', dateOfBirth: '1985-09-22', bloodGroup: 'O+',
    medicalConditions: [], allergies: [],
    insurance: { provider: 'HDFC ERGO Health' },
    emergencyContacts: [],
    status: 'active',
    governmentIdType: 'aadhaar', governmentIdNumber: '7766-5544-3322',
    createdAt: daysAgo(60), updatedAt: daysAgo(10),
  },
];

export const mockFamilies: Family[] = [
  {
    id: 'fam_1', userId: 'user_family_1', name: 'Sharma Family',
    primaryContactName: 'Rajesh Sharma',
    contact: { phone: '+91 98200 12345', email: 'rajesh.family@example.com' },
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    members: mockFamilyMembers,
    emergencyContacts: [{ name: 'Dr. V. K. Joshi (Family Doctor)', relationship: 'Doctor', phone: '+91 22 2840 9999' }],
    createdAt: daysAgo(90), updatedAt: daysAgo(1),
  },
];

export const mockCareProviders: CareProvider[] = [
    {
    id: 'prov_h1', name: 'Apollo Hospitals', type: 'hospital',
    description: 'Multi-specialty hospital network offering emergency admission coordination, ICU care, and specialist consultations for seniors.',
    contact: { phone: '+91 22 2692 5000', email: 'care@apollohospitals.com' },
    address: { line1: 'Mahalaxmi', city: 'Mumbai', state: 'Maharashtra', postalCode: '400034', country: 'India' },
    rating: 4.9, reviewCount: 720, isVerified: true,
    services: ['Emergency Admission', 'ICU Care', 'Specialist Consultation', 'Cardiac Care', 'Surgical Care'],
    experienceYears: 25, startingPrice: 3000, currency: '₹', distanceKm: 3.5, estimatedArrivalMinutes: 15, availability: 'available',
    employees: [
      { id: 'emp_prov_h1', name: 'Dr. Anil Kapoor', role: 'Senior Cardiologist', experience: '18 years', rating: 4.9, availability: 'Available today' },
      { id: 'emp_prov_h2', name: 'Dr. Priyanka Deshmukh', role: 'Emergency Medicine Specialist', experience: '12 years', rating: 4.8, availability: 'Available now' },
    ],
    reviews: [
      { id: 'rev_h1', reviewerName: 'Manoj T.', rating: 5, comment: 'Fastest emergency admission for my mother. Coordinated care from arrival to discharge.', createdAt: daysAgo(6) },
      { id: 'rev_h2', reviewerName: 'Kavita R.', rating: 5, comment: 'Trusted hospital network with excellent specialist doctors.', createdAt: daysAgo(18) },
    ],
    createdAt: daysAgo(400), updatedAt: daysAgo(1),
  },
  {
    id: 'prov_h2', name: 'KIMS Hospitals', type: 'hospital',
    description: 'Krishna Institute of Medical Sciences — leading multi-specialty hospital chain known for geriatric and critical care.',
    contact: { phone: '+91 22 2857 4000', email: 'contact@kimshospitals.com' },
    address: { line1: 'Saki Naka', city: 'Mumbai', state: 'Maharashtra', postalCode: '400072', country: 'India' },
    rating: 4.85, reviewCount: 540, isVerified: true,
    services: ['Emergency Admission', 'Geriatric Ward Care', 'Neurology', 'Orthopedic Surgery', 'Dialysis'],
    experienceYears: 20, startingPrice: 2800, currency: '₹', distanceKm: 5.1, estimatedArrivalMinutes: 20, availability: 'available',
    employees: [
      { id: 'emp_prov_h3', name: 'Dr. Ramesh Iyer', role: 'Senior Neurologist', experience: '16 years', rating: 4.85, availability: 'Available today' },
      { id: 'emp_prov_h4', name: 'Dr. Lakshmi Menon', role: 'Nephrologist', experience: '14 years', rating: 4.8, availability: 'Available tomorrow' },
    ],
    reviews: [
      { id: 'rev_h3', reviewerName: 'Ashwin P.', rating: 5, comment: 'KIMS took excellent care of my grandfather during his dialysis sessions.', createdAt: daysAgo(9) },
    ],
    createdAt: daysAgo(380), updatedAt: daysAgo(2),
  },
  {
    id: 'prov_h3', name: 'Fortis Healthcare', type: 'hospital',
    description: 'Nationally accredited hospital network with dedicated senior citizen care programs and 24/7 emergency response.',
    contact: { phone: '+91 22 6754 3333', email: 'care@fortishealthcare.com' },
    address: { line1: 'Mulund Goregaon Link Road', city: 'Mumbai', state: 'Maharashtra', postalCode: '400078', country: 'India' },
    rating: 4.8, reviewCount: 610, isVerified: true,
    services: ['Emergency Admission', 'Oncology', 'Cardiac Surgery', 'Senior Citizen Health Packages'],
    experienceYears: 22, startingPrice: 3200, currency: '₹', distanceKm: 6.2, estimatedArrivalMinutes: 22, availability: 'available',
    employees: [
      { id: 'emp_prov_h5', name: 'Dr. Neha Kulkarni', role: 'Senior Oncologist', experience: '17 years', rating: 4.8, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_h4', reviewerName: 'Rakesh S.', rating: 5, comment: 'Fortis handled my father\'s cardiac surgery with great care and clear communication.', createdAt: daysAgo(14) },
    ],
    createdAt: daysAgo(370), updatedAt: daysAgo(3),
  },
  {
    id: 'prov_h4', name: 'Manipal Hospitals', type: 'hospital',
    description: 'Comprehensive multi-specialty hospital chain offering advanced diagnostics, surgery, and elderly rehabilitation care.',
    contact: { phone: '+91 22 6969 6969', email: 'info@manipalhospitals.com' },
    address: { line1: 'Ghodbunder Road', city: 'Thane', state: 'Maharashtra', postalCode: '400607', country: 'India' },
    rating: 4.82, reviewCount: 495, isVerified: true,
    services: ['Emergency Admission', 'Advanced Diagnostics', 'Joint Replacement', 'Elderly Rehabilitation'],
    experienceYears: 19, startingPrice: 2700, currency: '₹', distanceKm: 8.4, estimatedArrivalMinutes: 28, availability: 'available',
    employees: [
      { id: 'emp_prov_h6', name: 'Dr. Sameer Joshi', role: 'Orthopedic Surgeon', experience: '15 years', rating: 4.82, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_h5', reviewerName: 'Deepa N.', rating: 5, comment: 'Smooth joint replacement surgery and thorough rehabilitation follow-up for my mother.', createdAt: daysAgo(22) },
    ],
    createdAt: daysAgo(360), updatedAt: daysAgo(4),
  },
  {
    id: 'prov_h5', name: 'Max Healthcare', type: 'hospital',
    description: 'Premier hospital network offering critical care, specialist consultations, and coordinated emergency transport for seniors.',
    contact: { phone: '+91 22 4933 4444', email: 'support@maxhealthcare.in' },
    address: { line1: 'Vikhroli West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400079', country: 'India' },
    rating: 4.88, reviewCount: 580, isVerified: true,
    services: ['Emergency Admission', 'Critical Care', 'Pulmonology', 'Senior Health Checkups'],
    experienceYears: 21, startingPrice: 3100, currency: '₹', distanceKm: 4.9, estimatedArrivalMinutes: 18, availability: 'available',
    employees: [
      { id: 'emp_prov_h7', name: 'Dr. Farhan Sheikh', role: 'Senior Pulmonologist', experience: '16 years', rating: 4.88, availability: 'Available now' },
    ],
    reviews: [
      { id: 'rev_h6', reviewerName: 'Sunita W.', rating: 5, comment: 'Max Healthcare\'s critical care team stabilized my father quickly during his emergency.', createdAt: daysAgo(11) },
    ],
    createdAt: daysAgo(350), updatedAt: daysAgo(1),
  },
  {
    id: 'prov_1', name: 'Aastha Senior Home Care & Rehab', type: 'home-care',
    description: 'Premier home healthcare & geriatric support. Experienced registered nurses, certified caregivers, and physiotherapists.',
    contact: { phone: '+91 22 4000 1111', email: 'care@aasthacare.in' },
    address: { line1: 'Linking Road, Bandra West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
    rating: 4.9, reviewCount: 184, isVerified: true,
    services: ['In-Home Nursing', 'Elderly Caregiver', 'Home Doctor Visit', 'Physiotherapy & Rehab', 'Sample Pickup'],
    experienceYears: 14, startingPrice: 1200, currency: '₹', distanceKm: 2.4, estimatedArrivalMinutes: 25, availability: 'available',
    employees: [
      { id: 'emp_prov_1', name: 'Anjali Sharma', role: 'Senior Registered Nurse', experience: '8 years', rating: 4.9, availability: 'Available today' },
      { id: 'emp_prov_2', name: 'Ritu Verma', role: 'Elderly Caregiver', experience: '5 years', rating: 4.7, availability: 'Available tomorrow' },
      { id: 'emp_prov_3', name: 'Rajesh Kumar', role: 'Senior Physiotherapist', experience: '6 years', rating: 4.8, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_1', reviewerName: 'Vikramaditya S.', rating: 5, comment: 'Outstanding home nursing for my father. Anjali was extremely attentive and caring.', createdAt: daysAgo(10) },
      { id: 'rev_2', reviewerName: 'Radhika M.', rating: 5, comment: 'Aastha Care has been supporting our family for 3 years. Most trustworthy service in Mumbai.', createdAt: daysAgo(20) },
      { id: 'rev_3', reviewerName: 'Suresh K.', rating: 4, comment: 'Prompt response and trained staff. My mother is very satisfied.', createdAt: daysAgo(35) },
    ],
    createdAt: daysAgo(200), updatedAt: daysAgo(1),
  },
  {
    id: 'prov_2', name: 'Jan Aushadhi Home Pharmacy', type: 'pharmacy',
    description: 'Fast home delivery of prescription medicines, chronic illness supplies, and OTC healthcare products.',
    contact: { phone: '+91 22 4000 2222', email: 'orders@janaushadhi.in' },
    address: { line1: 'Andheri East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400069', country: 'India' },
    rating: 4.7, reviewCount: 412, isVerified: true,
    services: ['Prescription Delivery', 'Chronic Medicine Refills', 'Medical Supplies', 'Refill Alerts'],
    experienceYears: 8, startingPrice: 200, currency: '₹', distanceKm: 3.8, estimatedArrivalMinutes: 45, availability: 'available',
    reviews: [
      { id: 'rev_4', reviewerName: 'Sneha P.', rating: 5, comment: 'Delivered within 40 minutes. Original medicines with proper invoice.', createdAt: daysAgo(5) },
    ],
    createdAt: daysAgo(150), updatedAt: daysAgo(3),
  },
  {
    id: 'prov_3', name: 'Sanjivani Diagnostic Labs', type: 'laboratory',
    description: 'NABL-accredited diagnostic laboratory with morning home sample collection and online reports within 12 hours.',
    contact: { phone: '+91 22 4000 3333', email: 'reports@sanjivanilab.in' },
    address: { line1: 'Powai Central', city: 'Mumbai', state: 'Maharashtra', postalCode: '400076', country: 'India' },
    rating: 4.85, reviewCount: 290, isVerified: true,
    services: ['Blood Test Collection', 'HbA1c & Lipid Panel', 'ECG at Home', 'Radiology Pickup'],
    experienceYears: 10, startingPrice: 600, currency: '₹', distanceKm: 4.5, estimatedArrivalMinutes: 60, availability: 'available',
    reviews: [
      { id: 'rev_5', reviewerName: 'Dr. Meenakshi S.', rating: 5, comment: 'Punctual phlebotomist and very accurate reports.', createdAt: daysAgo(8) },
    ],
    createdAt: daysAgo(180), updatedAt: daysAgo(2),
  },
  {
    id: 'prov_4', name: 'Chaitanya Rehab & Physio Center', type: 'physiotherapy',
    description: 'Specialized geriatric physiotherapy, knee/hip replacement rehab, stroke recovery, and posture correction.',
    contact: { phone: '+91 22 4000 4444', email: 'physio@chaitanya.in' },
    address: { line1: 'Juhu Tara Road', city: 'Mumbai', state: 'Maharashtra', postalCode: '400049', country: 'India' },
    rating: 4.8, reviewCount: 115, isVerified: true,
    services: ['Physiotherapy', 'Stroke Rehabilitation', 'Post-Surgery Rehab', 'Pain Relief Therapy'],
    experienceYears: 9, startingPrice: 1500, currency: '₹', distanceKm: 3.2, estimatedArrivalMinutes: 40, availability: 'busy',
    reviews: [],
    createdAt: daysAgo(120), updatedAt: daysAgo(4),
  },
  {
    id: 'prov_5', name: 'Dr. Malhotra House Call Physicians', type: 'doctor',
    description: 'Senior general physicians and geriatric specialists providing comprehensive medical consultations at home 24/7.',
    contact: { phone: '+91 22 4000 5555', email: 'doc@malhotracare.in' },
    address: { line1: 'Lower Parel', city: 'Mumbai', state: 'Maharashtra', postalCode: '400013', country: 'India' },
    rating: 4.95, reviewCount: 560, isVerified: true,
    services: ['Home Doctor Visit', 'Geriatric Health Review', 'Prescription Renewal', 'Emergency Doctor Response'],
    experienceYears: 18, startingPrice: 2500, currency: '₹', distanceKm: 1.9, estimatedArrivalMinutes: 20, availability: 'available',
    employees: [
      { id: 'emp_prov_4', name: 'Dr. Alok Gupta', role: 'Senior General Physician', experience: '15 years', rating: 4.95, availability: 'Available now' },
      { id: 'emp_prov_5', name: 'Dr. Sunita Rao', role: 'Geriatric Specialist', experience: '20 years', rating: 4.9, availability: 'Available today' },
    ],
    reviews: [
      { id: 'rev_6', reviewerName: 'Ramesh R.', rating: 5, comment: 'Dr. Alok examined my elderly father thoroughly. Very compassionate and empathetic.', createdAt: daysAgo(3) },
    ],
    createdAt: daysAgo(365), updatedAt: now(),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt_1', familyId: 'fam_1', memberId: 'mem_1', providerId: 'prov_5',
    providerName: 'Dr. Malhotra House Call Physicians — Dr. Alok Gupta', serviceType: 'Doctor Consultation',
    scheduledAt: daysFromNow(1), durationMinutes: 45, status: 'upcoming',
    notes: 'Monthly diabetes and vital checkup', location: 'Gokuldham Heights Flat 402',
    createdAt: hoursAgo(5), updatedAt: hoursAgo(4),
  },
  {
    id: 'apt_2', familyId: 'fam_1', memberId: 'mem_2', providerId: 'prov_4',
    providerName: 'Chaitanya Rehab — Rajesh Kumar', serviceType: 'Physiotherapy Session',
    scheduledAt: daysFromNow(3), durationMinutes: 60, status: 'upcoming',
    notes: 'Knee joint mobility session', location: 'Gokuldham Heights Flat 402',
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    id: 'apt_3', familyId: 'fam_1', memberId: 'mem_1', providerId: 'prov_3',
    providerName: 'Sanjivani Diagnostic Labs', serviceType: 'Blood Test Collection',
    scheduledAt: daysAgo(7), durationMinutes: 20, status: 'completed',
    notes: 'Fasting Glucose & HbA1c Panel', location: 'Home Collection',
    createdAt: daysAgo(10), updatedAt: daysAgo(7),
  },
];

export const mockTimeline: TimelineEntry[] = [
  { id: 'tl_1', familyId: 'fam_1', memberId: 'mem_1', eventType: 'care-request-submitted', title: 'Care Request Submitted', description: 'Home doctor consultation for Ramachandra Sharma requested.', createdAt: hoursAgo(5), updatedAt: hoursAgo(5) },
  { id: 'tl_2', familyId: 'fam_1', memberId: 'mem_1', eventType: 'care-request-accepted', title: 'Request Confirmed', description: 'Aastha Senior Care accepted the doctor visit request.', createdAt: hoursAgo(4), updatedAt: hoursAgo(4) },
  { id: 'tl_3', familyId: 'fam_1', memberId: 'mem_2', eventType: 'care-request-completed', title: 'Physiotherapy Completed', description: 'Physiotherapy session for Savitri Sharma completed.', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'tl_4', familyId: 'fam_1', memberId: 'mem_1', eventType: 'lab-test', title: 'Diagnostic Report Ready', description: 'HbA1c report available for Ramachandra Sharma.', createdAt: daysAgo(7), updatedAt: daysAgo(7) },
  { id: 'tl_5', familyId: 'fam_1', memberId: 'mem_1', eventType: 'medicine-delivered', title: 'Medicines Delivered', description: 'Monthly diabetes refill delivered by Jan Aushadhi.', createdAt: daysAgo(10), updatedAt: daysAgo(10) },
];

export const mockNotifications: Notification[] = [
  { id: 'notif_1', userId: 'user_family_1', title: 'Care Request Accepted', message: 'Aastha Senior Care has confirmed your request. Nurse Anjali will arrive tomorrow at 10:00 AM.', read: false, type: 'success', createdAt: hoursAgo(4), updatedAt: hoursAgo(4) },
  { id: 'notif_2', userId: 'user_family_1', title: 'Doctor Visit Tomorrow', message: 'Reminder: Dr. Alok Gupta visit for Ramachandra Sharma is scheduled for tomorrow at 10:00 AM.', read: false, type: 'info', createdAt: hoursAgo(2), updatedAt: hoursAgo(2) },
  { id: 'notif_3', userId: 'user_family_1', title: 'Physiotherapy Session In Progress', message: 'Rajesh Kumar has started the knee therapy session for Savitri Sharma.', read: true, type: 'info', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'notif_4', userId: 'user_family_1', title: 'Lab Results Uploaded', message: 'Fasting glucose results for Ramachandra Sharma are ready for viewing.', read: true, type: 'warning', createdAt: daysAgo(7), updatedAt: daysAgo(7) },
  { id: 'notif_5', userId: 'user_family_1', title: 'Medicine Delivery Complete', message: 'Insulin and hypertension kit delivered by Jan Aushadhi Pharmacy.', read: true, type: 'success', createdAt: daysAgo(10), updatedAt: daysAgo(10) },
  { id: 'notif_6', userId: 'user_family_1', title: 'Service Visit Completed', message: 'Home nursing visit by Nurse Anjali Sharma completed successfully.', read: true, type: 'success', createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: 'notif_7', userId: 'user_provider_1', title: 'New Care Request', message: 'Urgent caregiver request received for Devendra Patel.', read: false, type: 'warning', createdAt: hoursAgo(0.2), updatedAt: hoursAgo(0.2) },
  { id: 'notif_8', userId: 'user_provider_1', title: 'Staff On The Way', message: 'Nurse Anjali Sharma marked status as On The Way to Ramachandra Sharma residence.', read: false, type: 'info', createdAt: hoursAgo(0.3), updatedAt: hoursAgo(0.3) },
  { id: 'notif_9', userId: 'user_employee_1', title: 'New Field Assignment', message: 'You have been assigned to visit Ramachandra Sharma for Home Nursing Care.', read: false, type: 'success', createdAt: hoursAgo(1), updatedAt: hoursAgo(1) },
  { id: 'notif_10', userId: 'user_provider_1', title: '5-Star Review Received', message: 'Vikramaditya S. left a 5-star review for Anjali Sharma.', read: true, type: 'success', createdAt: daysAgo(5), updatedAt: daysAgo(5) },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp_1',
    name: 'Anjali Sharma',
    role: 'Senior Registered Nurse',
    department: 'Home Nursing Care',
    experience: '8 years',
    licenseNumber: 'INC-RN-88219-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98330 55512', email: 'anjali.s@aasthacare.in' },
    address: { line1: 'Dadar West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400028', country: 'India' },
    languages: ['Hindi', 'English', 'Marathi'],
    availability: 'available',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
    workingHours: '08:00 AM - 05:00 PM',
    governmentIdType: 'national-id',
    governmentIdNumber: '7841-1988-1234-1590',
    certificates: ['B.Sc Nursing', 'Basic Life Support (BLS)', 'Geriatric Care Specialist'],
    emergencyContact: { name: 'Suresh Sharma', relationship: 'Brother', phone: '+91 98220 99887' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-7885a3964478?auto=format&fit=crop&q=80&w=300',
    rating: 4.9,
    reviewCount: 42,
    assignedRequestsCount: 3,
    completedRequestsCount: 156,
    specialization: ['Geriatric Nursing', 'Wound Dressing', 'Diabetes Care'],
    createdAt: daysAgo(365),
    updatedAt: now(),
  },
  {
    id: 'emp_2',
    name: 'Ritu Verma',
    role: 'Elderly Caregiver',
    department: 'Home Care Services',
    experience: '5 years',
    licenseNumber: 'CG-45210-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98211 44322', email: 'ritu.v@aasthacare.in' },
    address: { line1: 'Goregaon East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    languages: ['Hindi', 'English'],
    availability: 'busy',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '09:00 AM - 06:00 PM',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '9988-1122-3344',
    certificates: ['Senior Companionship Certified', 'First Aid & CPR'],
    emergencyContact: { name: 'Kavita Verma', relationship: 'Sister', phone: '+91 98211 22110' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    rating: 4.7,
    reviewCount: 31,
    assignedRequestsCount: 2,
    completedRequestsCount: 104,
    specialization: ['Daily Living Support', 'Mobility Assistance', 'Dementia Support'],
    createdAt: daysAgo(300),
    updatedAt: now(),
  },
  {
    id: 'emp_3',
    name: 'Rajesh Kumar',
    role: 'Senior Physiotherapist',
    department: 'Rehabilitation',
    experience: '6 years',
    licenseNumber: 'BPT-99312-MUM',
    providerId: 'prov_1',
    contact: { phone: '+91 98335 88766', email: 'rajesh.k@aasthacare.in' },
    address: { line1: 'Mulund West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400080', country: 'India' },
    languages: ['Hindi', 'English', 'Marathi', 'Gujarati'],
    availability: 'available',
    workingDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    workingHours: '08:00 AM - 04:00 PM',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '5544-3322-1100',
    certificates: ['Master of Physiotherapy (MPT)', 'Stroke Rehabilitation Specialist'],
    emergencyContact: { name: 'Pooja Kumar', relationship: 'Wife', phone: '+91 98335 33445' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    rating: 4.85,
    reviewCount: 50,
    assignedRequestsCount: 1,
    completedRequestsCount: 128,
    specialization: ['Stroke Recovery', 'Knee/Joint Rehab', 'Posture Correction'],
    createdAt: daysAgo(250),
    updatedAt: now(),
  },
  {
    id: 'emp_4',
    name: 'Dr. Alok Gupta',
    role: 'General Physician',
    department: 'Medical Consultations',
    experience: '15 years',
    licenseNumber: 'MCI-MD-44812',
    providerId: 'prov_1',
    contact: { phone: '+91 98110 99900', email: 'alok.g@aasthacare.in' },
    address: { line1: 'Bandra Reclamation', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
    languages: ['Hindi', 'English'],
    availability: 'emergency_duty',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    workingHours: '24/7 On-Call Doctor',
    governmentIdType: 'national-id',
    governmentIdNumber: '7841-1982-9988-7766',
    certificates: ['MD Internal Medicine', 'Geriatric Health Specialist'],
    emergencyContact: { name: 'Dr. Meera Gupta', relationship: 'Wife', phone: '+91 98110 22110' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    rating: 4.95,
    reviewCount: 88,
    assignedRequestsCount: 4,
    completedRequestsCount: 260,
    specialization: ['Geriatric Care', 'Chronic Disease Management', 'Emergency Medicine'],
    createdAt: daysAgo(400),
    updatedAt: now(),
  },
  {
    id: 'emp_5',
    name: 'Suresh Patel',
    role: 'Emergency Medical Technician',
    department: 'Ambulance & Transport',
    experience: '7 years',
    licenseNumber: 'EMT-66120-MUM',
    providerId: 'prov_1',
    contact: { phone: '+971 98663 39988', email: 'suresh.p@aasthacare.in' },
    address: { line1: 'Thane West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400601', country: 'India' },
    languages: ['Hindi', 'English', 'Gujarati'],
    availability: 'available',
    workingDays: ['Everyday'],
    workingHours: 'Rotational Shift',
    governmentIdType: 'aadhaar',
    governmentIdNumber: '1122-3344-5566',
    certificates: ['Advanced Cardiac Life Support (ACLS)', 'Emergency Paramedic Level II'],
    emergencyContact: { name: 'Dinesh Patel', relationship: 'Father', phone: '+91 98663 44322' },
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
    rating: 4.85,
    reviewCount: 35,
    assignedRequestsCount: 0,
    completedRequestsCount: 95,
    specialization: ['Oxygen Administration', 'Trauma Response', 'Emergency Patient Transfer'],
    createdAt: daysAgo(180),
    updatedAt: now(),
  },
];

export const mockCareRequests: CareRequest[] = [
  {
    id: 'req_101',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_1',
    patientName: 'Ramachandra Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_1',
    employeeName: 'Anjali Sharma',
    employeeRole: 'Senior Registered Nurse',
    employeePhone: '+91 98330 55512',
    category: 'home-nurse',
    categoryLabel: 'Home Nurse Care',
    priority: 'urgent',
    status: 'on_the_way',
    scheduledAt: now(),
    notes: 'Urgent wound dressing & blood pressure vital check.',
    medicalNotes: 'Hypertension & Type 2 Diabetes. Patient takes morning insulin. Sensitive skin near knee area.',
    internalNotes: ['Family requested female nurse.', 'Assigned Anjali Sharma at 09:15 AM.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 1500,
    currency: '₹',
    estimatedArrivalMinutes: 12,
    estimatedDuration: '45 mins',
    timeline: [
      { status: 'pending', title: 'Request Submitted', description: 'Family requested urgent home nursing visit.', timestamp: hoursAgo(2) },
      { status: 'accepted', title: 'Request Accepted', description: 'Aastha Senior Care accepted the request.', timestamp: hoursAgo(1.5) },
      { status: 'employee_assigned', title: 'Nurse Assigned', description: 'Nurse Anjali Sharma assigned to visit.', timestamp: hoursAgo(1) },
      { status: 'on_the_way', title: 'Nurse On The Way', description: 'Anjali is en route with medical kit.', timestamp: hoursAgo(0.3) },
    ],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(0.3),
  },
  {
    id: 'req_102',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_2',
    patientName: 'Savitri Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_3',
    employeeName: 'Rajesh Kumar',
    employeeRole: 'Senior Physiotherapist',
    employeePhone: '+91 98335 88766',
    category: 'physiotherapy',
    categoryLabel: 'Physiotherapy Session',
    priority: 'standard',
    status: 'in_progress',
    scheduledAt: hoursAgo(1),
    notes: 'Bi-weekly knee arthritis mobility session.',
    medicalNotes: 'Severe joint stiffness in right knee. Avoid heavy weight bearing exercises.',
    internalNotes: ['Patient responded very well to warm up routine last session.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 1800,
    currency: '₹',
    estimatedArrivalMinutes: 0,
    estimatedDuration: '60 mins',
    timeline: [
      { status: 'pending', title: 'Booking Confirmed', description: 'Scheduled physiotherapy booked.', timestamp: daysAgo(1) },
      { status: 'accepted', title: 'Accepted', description: 'Provider confirmed slot.', timestamp: daysAgo(1) },
      { status: 'employee_assigned', title: 'Physiotherapist Assigned', description: 'Rajesh Kumar assigned.', timestamp: hoursAgo(3) },
      { status: 'arrived', title: 'Arrived at Location', description: 'Rajesh reached patient home.', timestamp: hoursAgo(1) },
      { status: 'in_progress', title: 'Session Started', description: 'Therapy exercises currently underway.', timestamp: hoursAgo(0.8) },
    ],
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(0.8),
  },
  {
    id: 'req_103',
    familyId: 'fam_1',
    familyName: 'Patel Family',
    memberId: 'mem_4',
    patientName: 'Devendra Patel',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    category: 'caregiver',
    categoryLabel: 'Caregiver Companionship',
    priority: 'emergency',
    status: 'pending',
    scheduledAt: daysFromNow(0.2),
    notes: 'Emergency caregiver needed due to family out of station.',
    medicalNotes: 'Dementia stage 1. Requires constant supervision & medication reminders.',
    internalNotes: [],
    address: { line1: 'Vasant Vihar Society 14', city: 'Mumbai', state: 'Maharashtra', postalCode: '400053', country: 'India' },
    estimatedCost: 1200,
    currency: '₹',
    estimatedArrivalMinutes: 20,
    estimatedDuration: '4 hours',
    timeline: [
      { status: 'pending', title: 'Emergency Request Submitted', description: 'Waiting for provider acceptance.', timestamp: hoursAgo(0.2) },
    ],
    createdAt: hoursAgo(0.2),
    updatedAt: hoursAgo(0.2),
  },
  {
    id: 'req_104',
    familyId: 'fam_1',
    familyName: 'Sharma Family',
    memberId: 'mem_1',
    patientName: 'Ramachandra Sharma',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_4',
    employeeName: 'Dr. Alok Gupta',
    employeeRole: 'General Physician',
    employeePhone: '+91 98110 99900',
    category: 'doctor',
    categoryLabel: 'Doctor Consultation',
    priority: 'scheduled',
    status: 'accepted',
    scheduledAt: daysFromNow(1),
    notes: 'Monthly diabetes and blood pressure evaluation.',
    medicalNotes: 'Diabetic history. Brings logbook of daily fasting glucose readings.',
    internalNotes: ['Dr. Alok confirmed schedule for tomorrow 10:00 AM.'],
    address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' },
    estimatedCost: 2500,
    currency: '₹',
    estimatedArrivalMinutes: 30,
    estimatedDuration: '45 mins',
    timeline: [
      { status: 'pending', title: 'Request Submitted', description: 'Doctor visit requested for tomorrow.', timestamp: hoursAgo(5) },
      { status: 'accepted', title: 'Request Accepted', description: 'Dr. Alok Gupta assigned & confirmed slot.', timestamp: hoursAgo(4) },
    ],
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'req_105',
    familyId: 'fam_1',
    familyName: 'Joshi Family',
    memberId: 'mem_5',
    patientName: 'Sunita Joshi',
    providerId: 'prov_1',
    providerName: 'Aastha Senior Home Care',
    employeeId: 'emp_1',
    employeeName: 'Anjali Sharma',
    employeeRole: 'Senior Registered Nurse',
    employeePhone: '+91 98330 55512',
    category: 'home-nurse',
    categoryLabel: 'Home Nurse Care',
    priority: 'standard',
    status: 'completed',
    scheduledAt: daysAgo(2),
    notes: 'IV fluid administration & general vital assessment.',
    medicalNotes: 'Mild dehydration. Administered 500ml Normal Saline as per prescription.',
    internalNotes: ['Completed smoothly. Patient felt much better.'],
    address: { line1: 'Shivaji Park, Building 5', city: 'Mumbai', state: 'Maharashtra', postalCode: '400028', country: 'India' },
    estimatedCost: 2000,
    currency: '₹',
    estimatedArrivalMinutes: 0,
    estimatedDuration: '90 mins',
    timeline: [
      { status: 'pending', title: 'Request Created', description: 'Nurse visit requested.', timestamp: daysAgo(3) },
      { status: 'accepted', title: 'Accepted', description: 'Provider confirmed.', timestamp: daysAgo(2.5) },
      { status: 'employee_assigned', title: 'Assigned', description: 'Nurse Anjali assigned.', timestamp: daysAgo(2.2) },
      { status: 'in_progress', title: 'In Progress', description: 'IV drip started.', timestamp: daysAgo(2) },
      { status: 'completed', title: 'Completed', description: 'Drip completed & vital signs stable.', timestamp: daysAgo(2) },
      { status: 'awaiting_review', title: 'Awaiting Review', description: 'Review link sent to family.', timestamp: daysAgo(2) },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
];

export const mockProviderServices: ProviderServiceItem[] = [
  { id: 'srv_1', name: 'In-Home Nursing Care', category: 'Home Nursing', description: 'Certified RN visits for wound care, injections, IV therapy & vital monitoring.', icon: 'HeartPulse', enabled: true, pricing: { amount: 1500, unit: 'per visit', currency: '₹' }, responseTime: '15-30 mins', coverageArea: 'Mumbai Metropolitan & Suburbs' },
  { id: 'srv_2', name: 'Elderly Caregiver Support', category: 'Caregiver', description: 'Compassionate assistance with daily living, hygiene, mobility & companionship.', icon: 'Users', enabled: true, pricing: { amount: 1000, unit: 'per 4 hrs', currency: '₹' }, responseTime: '30-45 mins', coverageArea: 'All Mumbai Zones' },
  { id: 'srv_3', name: 'Home Doctor Consultation', category: 'Doctor', description: 'Board-certified physicians for comprehensive health checkups & prescriptions at home.', icon: 'Stethoscope', enabled: true, pricing: { amount: 2500, unit: 'per visit', currency: '₹' }, responseTime: '20-40 mins', coverageArea: 'Mumbai & Thane' },
  { id: 'srv_4', name: 'Physiotherapy & Rehab', category: 'Physiotherapy', description: 'Customized physical rehabilitation for arthritis, post-stroke & joint mobility.', icon: 'Activity', enabled: true, pricing: { amount: 1800, unit: 'per session', currency: '₹' }, responseTime: '45-60 mins', coverageArea: 'Greater Mumbai' },
  { id: 'srv_5', name: 'Emergency Ambulance Transport', category: 'Ambulance', description: 'Rapid emergency dispatch with ICU-equipped ambulance & paramedic team.', icon: 'Ambulance', enabled: true, pricing: { amount: 3000, unit: 'per callout', currency: '₹' }, responseTime: '5-10 mins', coverageArea: '24/7 Citywide Coverage' },
  { id: 'srv_6', name: 'Diagnostic Lab Sample Pickup', category: 'Diagnostic Lab', description: 'Hygienic blood & sample collection at home with fast online lab results.', icon: 'FlaskConical', enabled: true, pricing: { amount: 600, unit: 'per pickup', currency: '₹' }, responseTime: '60 mins', coverageArea: 'All Districts' },
  { id: 'srv_7', name: 'Prescription Medicine Delivery', category: 'Pharmacy', description: 'Same-day home delivery of prescribed medications and OTC health supplies.', icon: 'Pill', enabled: true, pricing: { amount: 200, unit: 'per delivery', currency: '₹' }, responseTime: '30-60 mins', coverageArea: 'All Pin Codes' },
  { id: 'srv_8', name: 'Senior Wheelchair Transport', category: 'Transportation', description: 'Wheelchair-accessible vehicle transport for hospital visits & appointments.', icon: 'Car', enabled: true, pricing: { amount: 1200, unit: 'per trip', currency: '₹' }, responseTime: '20-30 mins', coverageArea: 'City Limits' },
  { id: 'srv_9', name: 'Senior Home Safety & Maintenance', category: 'Home Maintenance', description: 'Safety inspection, minor repairs, bathroom grab bar installation & light fixes.', icon: 'Wrench', enabled: true, pricing: { amount: 800, unit: 'per visit', currency: '₹' }, responseTime: '45 mins', coverageArea: 'Residential Complexes' },
  { id: 'srv_10', name: 'Senior Housekeeping & Sanitization', category: 'Housekeeping', description: 'Dust-free cleaning, linen changing & allergen sanitization for senior rooms.', icon: 'Home', enabled: false, pricing: { amount: 1000, unit: 'per session', currency: '₹' }, responseTime: '2 hours', coverageArea: 'Selected Pincodes' },
];

export const mockAvailabilityConfig: AvailabilityConfig = {
  businessHours: [
    { day: 'Monday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Tuesday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Wednesday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Thursday', open: '08:00', close: '20:00', isClosed: false },
    { day: 'Friday', open: '08:00', close: '18:00', isClosed: false },
    { day: 'Saturday', open: '09:00', close: '18:00', isClosed: false },
    { day: 'Sunday', open: '09:00', close: '16:00', isClosed: false },
  ],
  emergencyAvailable: true,
  holidaySchedule: [
    { date: '2026-08-15', name: 'Independence Day', isClosed: false },
    { date: '2026-10-02', name: 'Gandhi Jayanti', isClosed: true },
    { date: '2026-11-01', name: 'Diwali', isClosed: false },
  ],
  closedDays: ['Public Holidays (Restricted Hours)'],
  coverageRadiusKm: 35,
};

export const mockOrganizationProfile: OrganizationProfile = {
  id: 'prov_1',
  logoUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=200',
  name: 'Aastha Senior Home Care & Medical Services',
  registrationNumber: 'REG-MH-2012-9981',
  gstNumber: '27AAAAA0000A1Z5',
  verificationStatus: 'verified',
  address: { line1: 'Linking Road, Suite 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400050', country: 'India' },
  contact: { phone: '+91 22 4000 1111', email: 'care@aasthacare.in', alternativePhone: '+91 98100 98765' },
  website: 'https://aasthacare.in',
  businessHours: '08:00 AM - 08:00 PM (24/7 Emergency Response)',
  serviceCategories: ['Home Nursing', 'Elderly Caregiver', 'Physiotherapy', 'Doctor Visit', 'Emergency Ambulance'],
};

export const mockProviderDocuments: ProviderDocument[] = [
  { id: 'doc_1', title: 'Medical Facility License', type: 'license', fileName: 'Maharashtra_Medical_License_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(120), verificationStatus: 'verified', notes: 'Valid until Dec 2027' },
  { id: 'doc_2', title: 'Commercial Registration Certificate', type: 'registration', fileName: 'Registration_Certificate_Aastha.pdf', fileUrl: '#', uploadedAt: daysAgo(200), verificationStatus: 'verified' },
  { id: 'doc_3', title: 'GST Registration Certificate', type: 'gst', fileName: 'GST_Certificate_27AAAAA.pdf', fileUrl: '#', uploadedAt: daysAgo(200), verificationStatus: 'verified' },
  { id: 'doc_4', title: 'Medical Liability Insurance Policy', type: 'insurance', fileName: 'Medical_Liability_Insurance_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(45), verificationStatus: 'verified', notes: 'Coverage up to ₹50,00,000' },
  { id: 'doc_5', title: 'Staff Nursing License Certifications', type: 'employee', fileName: 'Staff_INC_Certificates_Q1.pdf', fileUrl: '#', uploadedAt: daysAgo(10), verificationStatus: 'verified' },
];

export const mockProviderReviewsExtended = [
  { id: 'rev_1', reviewerName: 'Vikramaditya S.', patientName: 'Ramachandra Sharma', rating: 5, comment: 'Exceptional care for my father. Nurse Anjali was patient, professional and extremely gentle.', createdAt: daysAgo(5), response: { text: 'Thank you Vikramaditya! It is our honor to support your father.', respondedAt: daysAgo(4) } },
  { id: 'rev_2', reviewerName: 'Radhika M.', patientName: 'Savitri Sharma', rating: 5, comment: 'We have used Aastha Care for two years. Best elderly service provider in Mumbai by far.', createdAt: daysAgo(12), response: undefined },
  { id: 'rev_3', reviewerName: 'Suresh K.', patientName: 'Tarun R.', rating: 4, comment: 'Reliable and trustworthy team. Response time for physiotherapy was very prompt.', createdAt: daysAgo(20), response: { text: 'We appreciate your valuable feedback Suresh!', respondedAt: daysAgo(19) } },
  { id: 'rev_4', reviewerName: 'Yash B.', patientName: 'Ananya B.', rating: 5, comment: 'Doctor consultation at home saved us an emergency hospital visit. Truly peace of mind.', createdAt: daysAgo(28), response: undefined },
];

export const mockServiceNotes: ServiceNote[] = [
  {
    id: 'sn_1',
    requestId: 'req_105',
    employeeId: 'emp_1',
    visitNotes: 'Administered IV hydration saline 500ml. Blood pressure 125/82, Heart rate 74 bpm. Temperature 36.8°C.',
    observations: 'Patient was initially fatigued but showed immediate energy recovery post hydration.',
    recommendations: 'Continue daily water intake of at least 2 liters. Recheck blood pressure in 3 days.',
    followUpNeeded: true,
    followUpDetails: 'Schedule follow up blood test if fatigue recurs.',
    attachments: [{ name: 'Vitals_Report_Sunita.pdf', url: '#' }],
    createdAt: daysAgo(2),
  },
];

export const mockBookings: Booking[] = [
  { id: 'book_1', familyId: 'fam_1', providerId: 'prov_1', serviceType: 'home-care', scheduledAt: now(), status: 'completed', employeeId: 'emp_1', createdAt: daysAgo(5), updatedAt: daysAgo(3) },
];

export const mockEmergencies: Emergency[] = [
  {
    id: 'emer_1', familyId: 'fam_1', memberId: 'mem_1', memberName: 'Ramachandra Sharma',
    status: 'active', currentStepIndex: 4,
    steps: [
      { step: 'sos_triggered', title: 'SOS Triggered', description: 'Emergency SOS activated by family', completedAt: hoursAgo(0.5), status: 'completed' },
      { step: 'location_detected', title: 'GPS Location Received', description: 'Location: Gokuldham Heights, Flat 402', completedAt: hoursAgo(0.48), status: 'completed' },
      { step: 'coordinator_activated', title: 'AI Coordinator Activated', description: 'Smart routing initiated', completedAt: hoursAgo(0.45), status: 'completed' },
      { step: 'provider_found', title: 'Provider Assigned', description: 'Aastha Senior Home Care dispatched', completedAt: hoursAgo(0.4), status: 'completed' },
      { step: 'professional_assigned', title: 'Employee Assigned', description: 'Dr. Alok Gupta en route', completedAt: hoursAgo(0.35), status: 'completed' },
      { step: 'ambulance_assigned', title: 'Ambulance Assigned', description: 'MH-02-AB-1234 dispatched', status: 'in-progress' },
      { step: 'hospital_notified', title: 'Hospital Notified', description: 'Kokilaben Hospital on standby', status: 'pending' },
      { step: 'contacts_notified', title: 'Contacts Notified', description: 'Emergency contacts alerted', status: 'pending' },
      { step: 'resolved', title: 'Emergency Resolved', description: 'Patient stabilized', status: 'pending' },
    ],
    location: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India', lat: 19.076, lng: 72.877 },
    assignedProvider: { id: 'prov_1', name: 'Aastha Senior Home Care', phone: '+91 22 4000 1111', etaMinutes: 8 },
    assignedProfessional: { id: 'emp_4', name: 'Dr. Alok Gupta', role: 'General Physician', phone: '+91 98110 99900' },
    assignedAmbulance: { vehicleNumber: 'MH-02-AB-1234', driverName: 'Suresh Patel', phone: '+91 98663 39988', etaMinutes: 6 },
    notifiedHospital: { name: 'Kokilaben Dhirubhai Ambani Hospital', phone: '+91 22 3099 9999', address: 'Andheri West, Mumbai' },
    notifiedContactsCount: 2,
    createdAt: hoursAgo(0.5), updatedAt: hoursAgo(0.2),
  },
  {
    id: 'emer_2', familyId: 'fam_2', memberId: 'mem_6', memberName: 'Lakshmi Nair',
    status: 'resolved', currentStepIndex: 8,
    steps: [
      { step: 'sos_triggered', title: 'SOS Triggered', description: 'Emergency SOS activated', completedAt: daysAgo(1), status: 'completed' },
      { step: 'location_detected', title: 'GPS Received', description: 'Location confirmed', completedAt: daysAgo(1), status: 'completed' },
      { step: 'coordinator_activated', title: 'AI Coordinator Activated', description: 'Routing initiated', completedAt: daysAgo(1), status: 'completed' },
      { step: 'provider_found', title: 'Provider Assigned', description: 'Chaitanya Rehab dispatched', completedAt: daysAgo(1), status: 'completed' },
      { step: 'professional_assigned', title: 'Employee Assigned', description: 'Nurse Priya Menon assigned', completedAt: daysAgo(1), status: 'completed' },
      { step: 'ambulance_assigned', title: 'Ambulance Assigned', description: 'Vehicle MH-04-CD-5678', completedAt: daysAgo(1), status: 'completed' },
      { step: 'hospital_notified', title: 'Hospital Notified', description: 'Lilavati Hospital alerted', completedAt: daysAgo(1), status: 'completed' },
      { step: 'contacts_notified', title: 'Contacts Notified', description: '3 contacts alerted', completedAt: daysAgo(1), status: 'completed' },
      { step: 'resolved', title: 'Emergency Resolved', description: 'Patient stabilized and admitted', completedAt: daysAgo(0.9), status: 'completed' },
    ],
    location: { line1: 'Bandra Kurla Complex', city: 'Mumbai', state: 'Maharashtra', postalCode: '400051', country: 'India' },
    assignedProvider: { id: 'prov_4', name: 'Chaitanya Rehab & Physio', phone: '+91 22 4000 4444', etaMinutes: 0 },
    assignedProfessional: { id: 'emp_6', name: 'Nurse Priya Menon', role: 'Senior Nurse', phone: '+91 98441 22330' },
    notifiedContactsCount: 3,
    createdAt: daysAgo(1), updatedAt: daysAgo(0.9),
  },
];

export const mockMedicalRecords: any[] = [];

// ── Admin-Specific Mock Data ────────────────────────────────────────────────

export const mockAdminFamilies: any[] = [
  { id: 'fam_1', userId: 'user_family_1', name: 'Sharma Family', primaryContactName: 'Rajesh Sharma', contact: { phone: '+91 98200 12345', email: 'rajesh.family@example.com' }, address: { line1: 'Gokuldham Heights, Flat 402', city: 'Mumbai', state: 'Maharashtra', postalCode: '400063', country: 'India' }, members: mockFamilyMembers, emergencyContacts: [{ name: 'Dr. V. K. Joshi', relationship: 'Doctor', phone: '+91 22 2840 9999' }], createdAt: daysAgo(90), updatedAt: daysAgo(1), activeRequestsCount: 2, totalRequestsCount: 12, emergencyCount: 1, status: 'active', lastActivity: hoursAgo(2) },
  { id: 'fam_2', userId: 'user_fam_2', name: 'Nair Family', primaryContactName: 'Krishnan Nair', contact: { phone: '+91 98441 55678', email: 'krishnan.nair@example.com' }, address: { line1: 'Bandra Kurla Complex, Tower B', city: 'Mumbai', state: 'Maharashtra', postalCode: '400051', country: 'India' }, members: [{ id: 'mem_6', familyId: 'fam_2', name: 'Lakshmi Nair', relationship: 'Mother', gender: 'female', dateOfBirth: '1950-03-20', bloodGroup: 'O+', medicalConditions: ['Heart Disease', 'Hypertension'], allergies: ['Sulfa drugs'], status: 'active', createdAt: daysAgo(60), updatedAt: daysAgo(3) }], createdAt: daysAgo(60), updatedAt: daysAgo(1), activeRequestsCount: 1, totalRequestsCount: 8, emergencyCount: 2, status: 'active', lastActivity: hoursAgo(5) },
  { id: 'fam_3', userId: 'user_fam_3', name: 'Iyer Family', primaryContactName: 'Venkatesh Iyer', contact: { phone: '+91 98330 44221', email: 'venkatesh.iyer@example.com' }, address: { line1: 'Matunga West, Shivaji Park Road', city: 'Mumbai', state: 'Maharashtra', postalCode: '400016', country: 'India' }, members: [{ id: 'mem_7', familyId: 'fam_3', name: 'Padmavathi Iyer', relationship: 'Grandmother', gender: 'female', dateOfBirth: '1942-07-12', bloodGroup: 'B+', medicalConditions: ['Dementia', 'Arthritis', 'Osteoporosis'], allergies: ['NSAIDs'], status: 'active', createdAt: daysAgo(120), updatedAt: daysAgo(2) }], createdAt: daysAgo(120), updatedAt: daysAgo(2), activeRequestsCount: 0, totalRequestsCount: 20, emergencyCount: 0, status: 'active', lastActivity: daysAgo(2) },
  { id: 'fam_4', userId: 'user_fam_4', name: 'Reddy Family', primaryContactName: 'Srinivas Reddy', contact: { phone: '+91 98880 11234', email: 'srinivas.reddy@example.com' }, address: { line1: 'Powai Lake View', city: 'Mumbai', state: 'Maharashtra', postalCode: '400076', country: 'India' }, members: [{ id: 'mem_8', familyId: 'fam_4', name: 'Venkamma Reddy', relationship: 'Mother', gender: 'female', dateOfBirth: '1955-11-08', bloodGroup: 'A-', medicalConditions: ['Kidney Disease', 'Diabetes'], allergies: [], status: 'active', createdAt: daysAgo(45), updatedAt: daysAgo(1) }], createdAt: daysAgo(45), updatedAt: daysAgo(1), activeRequestsCount: 3, totalRequestsCount: 5, emergencyCount: 1, status: 'flagged', lastActivity: hoursAgo(1) },
  { id: 'fam_5', userId: 'user_fam_5', name: 'Mehta Family', primaryContactName: 'Dilip Mehta', contact: { phone: '+91 98221 77890', email: 'dilip.mehta@example.com' }, address: { line1: 'Borivali West, Ekta Nagar', city: 'Mumbai', state: 'Maharashtra', postalCode: '400092', country: 'India' }, members: [{ id: 'mem_9', familyId: 'fam_5', name: 'Kantaben Mehta', relationship: 'Mother', gender: 'female', dateOfBirth: '1948-02-25', bloodGroup: 'B-', medicalConditions: ['Parkinson\'s Disease'], allergies: [], status: 'active', createdAt: daysAgo(30), updatedAt: daysAgo(5) }], createdAt: daysAgo(30), updatedAt: daysAgo(5), activeRequestsCount: 1, totalRequestsCount: 3, emergencyCount: 0, status: 'active', lastActivity: daysAgo(5) },
];

export const mockAdminProviders: any[] = [
  { ...mockCareProviders[0], verificationStatus: 'approved', employeeCount: 5, activeRequestsCount: 3, totalRequestsCount: 184, documentsCount: 5, pendingDocuments: 0, lastActivity: hoursAgo(1), submittedAt: daysAgo(200) },
  { ...mockCareProviders[1], verificationStatus: 'approved', employeeCount: 8, activeRequestsCount: 2, totalRequestsCount: 412, documentsCount: 4, pendingDocuments: 0, lastActivity: daysAgo(1), submittedAt: daysAgo(150) },
  { ...mockCareProviders[2], verificationStatus: 'approved', employeeCount: 12, activeRequestsCount: 5, totalRequestsCount: 290, documentsCount: 6, pendingDocuments: 0, lastActivity: daysAgo(2), submittedAt: daysAgo(180) },
  { ...mockCareProviders[3], verificationStatus: 'pending', employeeCount: 3, activeRequestsCount: 0, totalRequestsCount: 0, documentsCount: 2, pendingDocuments: 1, lastActivity: daysAgo(3), submittedAt: daysAgo(3) },
  { ...mockCareProviders[4], verificationStatus: 'approved', employeeCount: 6, activeRequestsCount: 4, totalRequestsCount: 560, documentsCount: 5, pendingDocuments: 0, lastActivity: hoursAgo(0.5), submittedAt: daysAgo(365) },
  { id: 'prov_6', name: 'Surya Multispecialty Home Care', type: 'home-care', description: 'Comprehensive home care specialists for post-surgical recovery and geriatric support.', contact: { phone: '+91 22 4000 6666', email: 'care@suryacare.in' }, address: { line1: 'Malad West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400064', country: 'India' }, rating: 0, reviewCount: 0, isVerified: false, services: ['Home Nursing', 'Post-Surgical Care', 'IV Therapy'], experienceYears: 3, startingPrice: 1000, currency: '₹', distanceKm: 5, estimatedArrivalMinutes: 40, availability: 'available', reviews: [], createdAt: daysAgo(5), updatedAt: daysAgo(1), verificationStatus: 'pending', employeeCount: 2, activeRequestsCount: 0, totalRequestsCount: 0, documentsCount: 3, pendingDocuments: 2, lastActivity: daysAgo(1), submittedAt: daysAgo(5) },
  { id: 'prov_7', name: 'Varsha Elder Care Services', type: 'caregiver', description: 'Senior companion and caregiver service for independent elderly.', contact: { phone: '+91 22 4000 7777', email: 'info@varshacare.in' }, address: { line1: 'Santacruz East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400055', country: 'India' }, rating: 3.5, reviewCount: 8, isVerified: false, services: ['Caregiver', 'Senior Transport', 'Housekeeping'], experienceYears: 1, startingPrice: 800, currency: '₹', distanceKm: 7, estimatedArrivalMinutes: 55, availability: 'available', reviews: [], createdAt: daysAgo(15), updatedAt: daysAgo(5), verificationStatus: 'rejected', employeeCount: 4, activeRequestsCount: 0, totalRequestsCount: 8, documentsCount: 2, pendingDocuments: 0, lastActivity: daysAgo(5), submittedAt: daysAgo(15), rejectionReason: 'Incomplete GST registration document. Missing NABL certification for claimed lab services.' },
];

export const mockAdminEmployees: any[] = [
  { ...mockEmployees[0], providerName: 'Aastha Senior Home Care', verificationStatus: 'approved', activeRequestsCount: 3 },
  { ...mockEmployees[1], providerName: 'Aastha Senior Home Care', verificationStatus: 'approved', activeRequestsCount: 2 },
  { ...mockEmployees[2], providerName: 'Aastha Senior Home Care', verificationStatus: 'approved', activeRequestsCount: 1 },
  { ...mockEmployees[3], providerName: 'Dr. Malhotra House Call Physicians', verificationStatus: 'approved', activeRequestsCount: 4 },
  { ...mockEmployees[4], providerName: 'Aastha Senior Home Care', verificationStatus: 'approved', activeRequestsCount: 0 },
  { id: 'emp_6', name: 'Priya Menon', role: 'Senior Registered Nurse', department: 'Home Nursing', experience: '6 years', licenseNumber: 'INC-RN-77441-MUM', providerId: 'prov_4', contact: { phone: '+91 98441 22330', email: 'priya.m@chaitanya.in' }, address: { line1: 'Kurla West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400070', country: 'India' }, languages: ['Malayalam', 'Hindi', 'English'], availability: 'available', workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], workingHours: '08:00 AM - 06:00 PM', governmentIdType: 'aadhaar', governmentIdNumber: '6655-4433-2211', certificates: ['B.Sc Nursing', 'Palliative Care Certificate'], emergencyContact: { name: 'Arun Menon', relationship: 'Husband', phone: '+91 98441 44556' }, status: 'active', avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300', rating: 4.8, reviewCount: 28, assignedRequestsCount: 1, completedRequestsCount: 88, specialization: ['Palliative Care', 'IV Therapy', 'Post-Surgical'], createdAt: daysAgo(200), updatedAt: now(), providerName: 'Chaitanya Rehab & Physio', verificationStatus: 'approved', activeRequestsCount: 1 },
  { id: 'emp_7', name: 'Ravi Shankar Pillai', role: 'Lab Technician', department: 'Diagnostics', experience: '4 years', licenseNumber: 'DMLT-33210-MUM', providerId: 'prov_3', contact: { phone: '+91 98773 11230', email: 'ravi.p@sanjivanilab.in' }, address: { line1: 'Andheri East', city: 'Mumbai', state: 'Maharashtra', postalCode: '400069', country: 'India' }, languages: ['Malayalam', 'Hindi', 'English'], availability: 'available', workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'], workingHours: '07:00 AM - 03:00 PM', governmentIdType: 'aadhaar', governmentIdNumber: '3344-5566-7788', certificates: ['DMLT', 'Phlebotomy Specialist'], status: 'active', avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=300', rating: 4.7, reviewCount: 19, assignedRequestsCount: 2, completedRequestsCount: 62, specialization: ['Blood Collection', 'Rapid Antigen', 'ECG Recording'], createdAt: daysAgo(130), updatedAt: now(), providerName: 'Sanjivani Diagnostic Labs', verificationStatus: 'pending', activeRequestsCount: 2 },
];

export const mockVerificationQueue: any[] = [
  {
    id: 'ver_1', entityType: 'provider', entityId: 'prov_6', entityName: 'Surya Multispecialty Home Care', organizationName: 'Surya Healthcare Pvt Ltd', contactEmail: 'care@suryacare.in', contactPhone: '+91 22 4000 6666', submittedAt: daysAgo(5), status: 'pending',
    registrationNumber: 'REG-MH-2024-1234', gstNumber: '27BBBBB1111B1Z5', licenseNumber: 'MH-MED-2024-5678',
    documents: [
      { id: 'vdoc_1', title: 'Business Registration Certificate', type: 'registration', fileName: 'Surya_Registration.pdf', fileUrl: '#', uploadedAt: daysAgo(5), status: 'pending' },
      { id: 'vdoc_2', title: 'GST Registration', type: 'gst', fileName: 'Surya_GST.pdf', fileUrl: '#', uploadedAt: daysAgo(5), status: 'verified' },
      { id: 'vdoc_3', title: 'Medical Facility License', type: 'license', fileName: 'Surya_License.pdf', fileUrl: '#', uploadedAt: daysAgo(4), status: 'pending', notes: 'Needs Maharashtra Medical Council stamp' },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1504813184591-01572f98c85f?auto=format&fit=crop&q=80&w=200',
    notes: 'New provider from Malad West. Has 2 qualified nurses on roster.',
  },
  {
    id: 'ver_2', entityType: 'employee', entityId: 'emp_7', entityName: 'Ravi Shankar Pillai', organizationName: 'Sanjivani Diagnostic Labs', contactEmail: 'ravi.p@sanjivanilab.in', contactPhone: '+91 98773 11230', submittedAt: daysAgo(2), status: 'pending',
    licenseNumber: 'DMLT-33210-MUM',
    documents: [
      { id: 'vdoc_4', title: 'DMLT Certificate', type: 'certificate', fileName: 'DMLT_Ravi_Pillai.pdf', fileUrl: '#', uploadedAt: daysAgo(2), status: 'pending' },
      { id: 'vdoc_5', title: 'Aadhaar ID', type: 'other', fileName: 'Aadhaar_Ravi.pdf', fileUrl: '#', uploadedAt: daysAgo(2), status: 'verified' },
      { id: 'vdoc_6', title: 'Police Verification', type: 'other', fileName: 'Police_Verification_Ravi.pdf', fileUrl: '#', uploadedAt: daysAgo(1), status: 'pending' },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'ver_3', entityType: 'provider', entityId: 'prov_7', entityName: 'Varsha Elder Care Services', organizationName: 'Varsha Senior Services', contactEmail: 'info@varshacare.in', contactPhone: '+91 22 4000 7777', submittedAt: daysAgo(15), status: 'rejected',
    registrationNumber: 'REG-MH-2025-7891',
    documents: [
      { id: 'vdoc_7', title: 'Business Registration', type: 'registration', fileName: 'Varsha_Reg.pdf', fileUrl: '#', uploadedAt: daysAgo(15), status: 'verified' },
      { id: 'vdoc_8', title: 'GST Certificate', type: 'gst', fileName: 'Varsha_GST.pdf', fileUrl: '#', uploadedAt: daysAgo(15), status: 'rejected', notes: 'GST number invalid — does not match MCA records' },
    ],
    rejectionReason: 'Incomplete GST registration document. Missing NABL certification for claimed lab services.',
    reviewedBy: 'Ananya Verma (Administrator)', reviewedAt: daysAgo(10),
    avatarUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=200',
  },
];

export const mockServiceCategories: any[] = [
  {
    id: 'cat_1',
    name: 'Healthcare',
    icon: 'Building2',
    description: 'Hospitals, clinics & specialists',
    color: '#3B82F6',
    enabled: true,
    providerCount: 12,
    requestCount: 234,
    createdAt: daysAgo(400),
    items: [
      { name: 'Hospitals', icon: 'Building2' },
      { name: 'Clinics', icon: 'Stethoscope' },
      { name: 'Family physicians', icon: 'HeartHandshake' },
      { name: 'Specialists', icon: 'Brain' },
    ],
  },
  {
    id: 'cat_2',
    name: 'Diagnostics',
    icon: 'FlaskConical',
    description: 'Tests & sample collection',
    color: '#F59E0B',
    enabled: true,
    providerCount: 8,
    requestCount: 176,
    createdAt: daysAgo(400),
    items: [
      { name: 'Blood tests', icon: 'TestTube' },
      { name: 'X-rays', icon: 'Scan' },
      { name: 'ECG', icon: 'HeartPulse' },
      { name: 'Home sample collection', icon: 'Home' },
    ],
  },
  {
    id: 'cat_3',
    name: 'Pharmacy',
    icon: 'Pill',
    description: 'Medicines & prescriptions',
    color: '#10B981',
    enabled: true,
    providerCount: 5,
    requestCount: 412,
    createdAt: daysAgo(400),
    items: [
      { name: 'Medicine delivery', icon: 'Pill' },
      { name: 'Prescription management', icon: 'FileText' },
    ],
  },
  {
    id: 'cat_4',
    name: 'Home care',
    icon: 'Activity',
    description: 'Skilled support at home',
    color: '#EC4899',
    enabled: true,
    providerCount: 9,
    requestCount: 310,
    createdAt: daysAgo(400),
    items: [
      { name: 'Nurses', icon: 'Activity' },
      { name: 'Physiotherapists', icon: 'Dumbbell' },
      { name: 'Care attendants', icon: 'Users' },
    ],
  },
  {
    id: 'cat_5',
    name: 'Home services',
    icon: 'Wrench',
    description: 'Everyday household help',
    color: '#8B5CF6',
    enabled: true,
    providerCount: 6,
    requestCount: 89,
    createdAt: daysAgo(400),
    items: [
      { name: 'Electricians', icon: 'Zap' },
      { name: 'Plumbers', icon: 'Droplet' },
      { name: 'Appliance repair', icon: 'Wrench' },
      { name: 'House cleaning', icon: 'Sparkles' },
      { name: 'Pest control', icon: 'Bug' },
    ],
  },
  {
    id: 'cat_6',
    name: 'Transportation',
    icon: 'Car',
    description: 'Getting there, safely',
    color: '#6366F1',
    enabled: true,
    providerCount: 4,
    requestCount: 95,
    createdAt: daysAgo(400),
    items: [
      { name: 'Ambulance', icon: 'Ambulance' },
      { name: 'Taxi partners', icon: 'Car' },
      { name: 'Wheelchair transport', icon: 'Accessibility' },
    ],
  },
  {
    id: 'cat_7',
    name: 'Emergency contacts',
    icon: 'Siren',
    description: 'Help close to home',
    color: '#EF4444',
    enabled: true,
    providerCount: 15,
    requestCount: 54,
    createdAt: daysAgo(400),
    items: [
      { name: 'Local relatives', icon: 'Users' },
      { name: 'Neighbors', icon: 'Home' },
      { name: 'Apartment association', icon: 'Building2' },
      { name: 'Police (where appropriate)', icon: 'ShieldAlert' },
    ],
  },
];

export const mockAdminReviews: any[] = [
  { id: 'rev_a1', reviewerName: 'Vikramaditya S.', reviewerFamilyId: 'fam_1', providerId: 'prov_1', providerName: 'Aastha Senior Home Care', employeeId: 'emp_1', employeeName: 'Anjali Sharma', patientName: 'Ramachandra Sharma', rating: 5, comment: 'Exceptional home nursing for my father. Anjali was patient, professional and extremely gentle.', isComplaint: false, status: 'responded', response: { text: 'Thank you Vikramaditya! It is our honor to support your father.', respondedAt: daysAgo(4) }, createdAt: daysAgo(5) },
  { id: 'rev_a2', reviewerName: 'Radhika M.', reviewerFamilyId: 'fam_3', providerId: 'prov_1', providerName: 'Aastha Senior Home Care', patientName: 'Padmavathi Iyer', rating: 5, comment: 'Aastha Care has been with us for 2 years. Absolutely the most trusted elderly care in Mumbai.', isComplaint: false, status: 'pending', createdAt: daysAgo(12) },
  { id: 'rev_a3', reviewerName: 'Suresh K.', reviewerFamilyId: 'fam_2', providerId: 'prov_4', providerName: 'Chaitanya Rehab', employeeId: 'emp_3', employeeName: 'Rajesh Kumar', patientName: 'Lakshmi Nair', rating: 4, comment: 'Good physiotherapy session. Rajesh was punctual and professional.', isComplaint: false, status: 'responded', response: { text: 'Thank you for your feedback!', respondedAt: daysAgo(19) }, createdAt: daysAgo(20) },
  { id: 'rev_a4', reviewerName: 'Dinesh Patel', reviewerFamilyId: 'fam_4', providerId: 'prov_7', providerName: 'Varsha Elder Care Services', rating: 2, comment: 'Caregiver arrived 3 hours late and did not bring proper medical supplies. Very disappointed.', isComplaint: true, status: 'flagged', createdAt: daysAgo(7) },
  { id: 'rev_a5', reviewerName: 'Meena Iyer', reviewerFamilyId: 'fam_3', providerId: 'prov_3', providerName: 'Sanjivani Diagnostic Labs', employeeId: 'emp_7', employeeName: 'Ravi Shankar Pillai', patientName: 'Padmavathi Iyer', rating: 5, comment: 'Punctual blood sample collection. Reports arrived within 10 hours. Excellent service!', isComplaint: false, status: 'responded', response: { text: 'Thank you Meena ji! We aim to serve you at the highest standard.', respondedAt: daysAgo(1) }, createdAt: daysAgo(3) },
  { id: 'rev_a6', reviewerName: 'Srinivas R.', reviewerFamilyId: 'fam_4', providerId: 'prov_2', providerName: 'Jan Aushadhi Home Pharmacy', rating: 3, comment: 'Medicine was delivered but wrong dosage was sent. Had to call multiple times for correction.', isComplaint: true, status: 'resolved', response: { text: 'We sincerely apologize for the error. We have re-verified our medication dispatch process.', respondedAt: daysAgo(6) }, createdAt: daysAgo(8) },
];

export const mockAdminNotifications: any[] = [
  { id: 'an_1', type: 'emergency', title: '🚨 Active Emergency — Sharma Family', message: 'SOS triggered by Ramachandra Sharma (Gokuldham Heights). Dr. Alok Gupta & ambulance dispatched. ETA 8 mins.', priority: 'critical', read: false, entityId: 'emer_1', entityType: 'emergency', createdAt: hoursAgo(0.5) },
  { id: 'an_2', type: 'verification', title: 'New Provider Verification Request', message: 'Surya Multispecialty Home Care submitted verification documents. 3 documents pending review.', priority: 'high', read: false, entityId: 'ver_1', entityType: 'verification', createdAt: daysAgo(5) },
  { id: 'an_3', type: 'verification', title: 'Employee Verification Pending', message: 'Ravi Shankar Pillai (Sanjivani Labs) has submitted DMLT and Aadhaar documents. Awaiting police verification.', priority: 'medium', read: false, entityId: 'ver_2', entityType: 'verification', createdAt: daysAgo(2) },
  { id: 'an_4', type: 'provider', title: 'Low-Rated Complaint Received', message: 'Dinesh Patel filed a complaint against Varsha Elder Care Services (2-star rating). Review flagged for administrator action.', priority: 'high', read: false, entityId: 'rev_a4', entityType: 'review', createdAt: daysAgo(7) },
  { id: 'an_5', type: 'system', title: 'Platform Health: 98%', message: 'All services operational. API response time 142ms average. 0 critical errors in last 24 hours.', priority: 'low', read: true, createdAt: hoursAgo(3) },
  { id: 'an_6', type: 'provider', title: 'Provider Varsha Care Rejected', message: 'Varsha Elder Care Services verification rejected. GST number mismatch. Provider notified automatically.', priority: 'medium', read: true, entityId: 'prov_7', entityType: 'provider', createdAt: daysAgo(10) },
  { id: 'an_7', type: 'announcement', title: 'Diwali Support Hours Update', message: 'Emergency services remain 24/7. Routine home care requests may experience 20% longer ETAs on Nov 1.', priority: 'low', read: true, createdAt: daysAgo(15) },
];

export const mockAdminDocuments: any[] = [
  { id: 'adoc_1', title: 'Maharashtra Medical License 2026', type: 'license', fileName: 'Aastha_License_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(120), status: 'verified', notes: 'Valid until Dec 2027', ownerName: 'Aastha Senior Home Care', ownerType: 'provider', ownerId: 'prov_1', providerName: 'Aastha Senior Home Care' },
  { id: 'adoc_2', title: 'GST Registration Certificate', type: 'gst', fileName: 'Aastha_GST.pdf', fileUrl: '#', uploadedAt: daysAgo(200), status: 'verified', ownerName: 'Aastha Senior Home Care', ownerType: 'provider', ownerId: 'prov_1', providerName: 'Aastha Senior Home Care' },
  { id: 'adoc_3', title: 'INC Nursing License — Anjali Sharma', type: 'license', fileName: 'INC_Anjali_Sharma.pdf', fileUrl: '#', uploadedAt: daysAgo(365), status: 'verified', ownerName: 'Anjali Sharma', ownerType: 'employee', ownerId: 'emp_1', providerName: 'Aastha Senior Home Care' },
  { id: 'adoc_4', title: 'DMLT Certificate — Ravi Shankar Pillai', type: 'certificate', fileName: 'DMLT_Ravi_Pillai.pdf', fileUrl: '#', uploadedAt: daysAgo(2), status: 'pending', ownerName: 'Ravi Shankar Pillai', ownerType: 'employee', ownerId: 'emp_7', providerName: 'Sanjivani Diagnostic Labs' },
  { id: 'adoc_5', title: 'Business Registration — Surya Multispecialty', type: 'registration', fileName: 'Surya_Registration.pdf', fileUrl: '#', uploadedAt: daysAgo(5), status: 'pending', ownerName: 'Surya Multispecialty Home Care', ownerType: 'provider', ownerId: 'prov_6', providerName: 'Surya Multispecialty Home Care' },
  { id: 'adoc_6', title: 'NABL Lab Accreditation', type: 'certificate', fileName: 'NABL_Sanjivani_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(180), status: 'verified', notes: 'Valid until March 2028', ownerName: 'Sanjivani Diagnostic Labs', ownerType: 'provider', ownerId: 'prov_3', providerName: 'Sanjivani Diagnostic Labs' },
  { id: 'adoc_7', title: 'Medical Liability Insurance', type: 'insurance', fileName: 'Aastha_Insurance_2026.pdf', fileUrl: '#', uploadedAt: daysAgo(45), status: 'verified', notes: 'Coverage ₹50,00,000', ownerName: 'Aastha Senior Home Care', ownerType: 'provider', ownerId: 'prov_1', providerName: 'Aastha Senior Home Care' },
  { id: 'adoc_8', title: 'GST Certificate — Varsha Care', type: 'gst', fileName: 'Varsha_GST.pdf', fileUrl: '#', uploadedAt: daysAgo(15), status: 'rejected', notes: 'GST number invalid — does not match MCA records', ownerName: 'Varsha Elder Care Services', ownerType: 'provider', ownerId: 'prov_7', providerName: 'Varsha Elder Care Services' },
];

export const mockPlatformActivities: any[] = [
  { id: 'act_1', type: 'sos_triggered', title: 'Emergency SOS Triggered', description: 'Ramachandra Sharma (Sharma Family) triggered SOS at Gokuldham Heights', actorName: 'Rajesh Sharma', actorRole: 'family', entityId: 'emer_1', entityType: 'emergency', severity: 'critical', createdAt: hoursAgo(0.5) },
  { id: 'act_2', type: 'care_requested', title: 'New Care Request', description: 'Patel Family requested emergency caregiver for Devendra Patel', actorName: 'Patel Family', actorRole: 'family', entityId: 'req_103', entityType: 'request', severity: 'warning', createdAt: hoursAgo(0.2) },
  { id: 'act_3', type: 'provider_approved', title: 'Provider Approved', description: 'Sanjivani Diagnostic Labs verified and approved', actorName: 'Ananya Verma', actorRole: 'admin', entityId: 'prov_3', entityType: 'provider', severity: 'info', createdAt: daysAgo(2) },
  { id: 'act_4', type: 'request_completed', title: 'Care Request Completed', description: 'Anjali Sharma completed IV hydration for Sunita Joshi (Joshi Family)', actorName: 'Anjali Sharma', actorRole: 'employee', entityId: 'req_105', entityType: 'request', severity: 'info', createdAt: daysAgo(2) },
  { id: 'act_5', type: 'review_submitted', title: 'Review Submitted', description: 'Vikramaditya S. left a 5-star review for Aastha Senior Home Care', actorName: 'Vikramaditya S.', actorRole: 'family', entityId: 'rev_a1', entityType: 'review', severity: 'info', createdAt: daysAgo(5) },
  { id: 'act_6', type: 'provider_registered', title: 'New Provider Registered', description: 'Surya Multispecialty Home Care submitted registration for verification', actorName: 'Surya Multispecialty', actorRole: 'care-provider', entityId: 'prov_6', entityType: 'provider', severity: 'info', createdAt: daysAgo(5) },
  { id: 'act_7', type: 'emergency_resolved', title: 'Emergency Resolved', description: 'Lakshmi Nair (Nair Family) emergency resolved. Patient admitted at Lilavati Hospital.', actorName: 'System', actorRole: 'system', entityId: 'emer_2', entityType: 'emergency', severity: 'info', createdAt: daysAgo(1) },
  { id: 'act_8', type: 'family_registered', title: 'New Family Registered', description: 'Mehta Family registered. Primary contact: Dilip Mehta (Borivali West)', actorName: 'Dilip Mehta', actorRole: 'family', entityId: 'fam_5', entityType: 'family', severity: 'info', createdAt: daysAgo(30) },
  { id: 'act_9', type: 'employee_verified', title: 'Employee Verified', description: 'Anjali Sharma (Aastha Care) INC nursing license verified and activated', actorName: 'Ananya Verma', actorRole: 'admin', entityId: 'emp_1', entityType: 'employee', severity: 'info', createdAt: daysAgo(365) },
  { id: 'act_10', type: 'document_uploaded', title: 'Document Uploaded', description: 'DMLT Certificate uploaded by Ravi Shankar Pillai for verification', actorName: 'Ravi Shankar Pillai', actorRole: 'employee', entityId: 'adoc_4', entityType: 'document', severity: 'info', createdAt: daysAgo(2) },
];

export const mockPlatformAnalytics: any = {
  familyGrowth: [
    { month: 'Feb', count: 1 }, { month: 'Mar', count: 2 }, { month: 'Apr', count: 3 },
    { month: 'May', count: 3 }, { month: 'Jun', count: 4 }, { month: 'Jul', count: 5 }, { month: 'Aug', count: 5 },
  ],
  providerGrowth: [
    { month: 'Feb', count: 3 }, { month: 'Mar', count: 3 }, { month: 'Apr', count: 4 },
    { month: 'May', count: 5 }, { month: 'Jun', count: 5 }, { month: 'Jul', count: 6 }, { month: 'Aug', count: 7 },
  ],
  employeeGrowth: [
    { month: 'Feb', count: 3 }, { month: 'Mar', count: 4 }, { month: 'Apr', count: 5 },
    { month: 'May', count: 5 }, { month: 'Jun', count: 6 }, { month: 'Jul', count: 7 }, { month: 'Aug', count: 7 },
  ],
  requestTrends: [
    { month: 'Feb', total: 18, emergency: 1, completed: 16 }, { month: 'Mar', total: 24, emergency: 2, completed: 22 },
    { month: 'Apr', total: 31, emergency: 3, completed: 28 }, { month: 'May', total: 38, emergency: 2, completed: 35 },
    { month: 'Jun', total: 42, emergency: 4, completed: 38 }, { month: 'Jul', total: 50, emergency: 3, completed: 45 }, { month: 'Aug', total: 12, emergency: 1, completed: 8 },
  ],
  emergencyTrends: [
    { month: 'Feb', count: 1, avgResponseMins: 14 }, { month: 'Mar', count: 2, avgResponseMins: 12 },
    { month: 'Apr', count: 3, avgResponseMins: 10 }, { month: 'May', count: 2, avgResponseMins: 11 },
    { month: 'Jun', count: 4, avgResponseMins: 9 }, { month: 'Jul', count: 3, avgResponseMins: 8 }, { month: 'Aug', count: 1, avgResponseMins: 8 },
  ],
  categoryUsage: [
    { category: 'Home Nursing', count: 210, percentage: 27 }, { category: 'Medicine Delivery', count: 178, percentage: 23 },
    { category: 'Diagnostic Lab', count: 120, percentage: 15 }, { category: 'Doctor Visit', count: 98, percentage: 13 },
    { category: 'Physiotherapy', count: 75, percentage: 10 }, { category: 'Elderly Caregiver', count: 60, percentage: 8 },
    { category: 'Others', count: 30, percentage: 4 },
  ],
  ratingsDistribution: [
    { rating: 5, count: 142 }, { rating: 4, count: 89 }, { rating: 3, count: 28 }, { rating: 2, count: 8 }, { rating: 1, count: 3 },
  ],
  avgResponseTimeMinutes: 18,
  topProviders: [
    { id: 'prov_5', name: 'Dr. Malhotra House Call Physicians', rating: 4.95, requestCount: 560 },
    { id: 'prov_1', name: 'Aastha Senior Home Care', rating: 4.9, requestCount: 184 },
    { id: 'prov_3', name: 'Sanjivani Diagnostic Labs', rating: 4.85, requestCount: 290 },
    { id: 'prov_4', name: 'Chaitanya Rehab & Physio', rating: 4.8, requestCount: 115 },
    { id: 'prov_2', name: 'Jan Aushadhi Home Pharmacy', rating: 4.7, requestCount: 412 },
  ],
  topEmployees: [
    { id: 'emp_4', name: 'Dr. Alok Gupta', rating: 4.95, completedCount: 260 },
    { id: 'emp_1', name: 'Anjali Sharma', rating: 4.9, completedCount: 156 },
    { id: 'emp_3', name: 'Rajesh Kumar', rating: 4.85, completedCount: 128 },
    { id: 'emp_5', name: 'Suresh Patel', rating: 4.85, completedCount: 95 },
    { id: 'emp_2', name: 'Ritu Verma', rating: 4.7, completedCount: 104 },
  ],
  mostRequestedServices: [
    { service: 'In-Home Nursing Care', count: 210 }, { service: 'Medicine Delivery', count: 178 },
    { service: 'Blood Test Collection', count: 120 }, { service: 'Doctor Consultation', count: 98 },
    { service: 'Physiotherapy Session', count: 75 }, { service: 'Elderly Caregiver', count: 60 },
  ],
};

export const mockPlatformSettings: any = {
  platformName: 'We Care For You', platformTagline: 'AI-Powered Care Coordination Platform', supportEmail: 'support@wecare4you.app', supportPhone: '+91 98000 00000', defaultLanguage: 'en', timezone: 'Asia/Kolkata', currency: 'INR', currencySymbol: '₹', emergencyResponseTargetMinutes: 10, verificationRequiredForProviders: true, verificationRequiredForEmployees: true, allowSelfRegistration: true, maxFamilyMembers: 10,
  notifications: { emailEnabled: true, smsEnabled: true, pushEnabled: true, emergencyAlerts: true, verificationAlerts: true, systemAlerts: true },
  theme: { primaryColor: '#0F172A', accentColor: '#F97316', darkModeDefault: false },
  pwa: { enabled: true, offlineSupport: true, backgroundSync: true },
};

